In [142]:

import bs4
from bs4 import BeautifulSoup
import requests

In [143]:
url="https://www.worldometers.info/world-population/population-by-country/"
page=requests.get(url)
page.encoding = 'utf-8'    #useful for encoding sysmbols % - + etc
print(page)

<Response [200]>

In [144]:
soup=BeautifulSoup(page.text,'html')
soup

<!DOCTYPE html>
<html data-astro-transition-scope="astro-s7reefwf-2" dir="ltr" lang="en"> <head><meta charset="utf-8"/><meta content="IE=edge" http-equiv="X-UA-Compatible"/><meta content="width=device-width, initial-scale=1" name="viewport"/><title>Population by Country (2025) - Worldometer</title><!-- <I18nTags /> --><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-ZDP3BFSX60"></script> <script>
  window.dataLayer = window.dataLayer || [];
  function gtag() {
    // eslint-disable-next-line prefer-rest-params
    dataLayer.push(arguments);
  }
  gtag("js", new Date());
  gtag("config", "G-ZDP3BFSX60", {
    page_lang: document.documentElement.lang,
  });
</script><script crossorigin="anonymous" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3701697624350410"></script> <script async="" src="https://securepubads.g.doubleclick.net/tag/js/gpt.js"></script> <link crossorigin="" href="https://a.pub.network/" rel="preconnect"/><link crossorigin="" href="https://b.pub.network/" rel="preconnect"/><link crossorigin="" href="https://c.pub.network/" rel="preconnect"/><link crossorigin="" href="https://d.pub.network/" rel="preconnect"/><link crossorigin="" href="https://c.amazon-adsystem.com" rel="preconnect"/><link crossorigin="" href="https://s.amazon-adsystem.com" rel="preconnect"/><link crossorigin="" href="https://btloader.com/" rel="preconnect"/><link crossorigin="" href="https://api.btloader.com/" rel="preconnect"/><link crossorigin="" href="https://cdn.confiant-integrations.net" rel="preconnect"/><!-- Below is a link to a CSS file that accounts for Cumulative Layout Shift --><!-- The file is intended to eliminate the layout shifts that are seen when ads load into the page. If you don't want to use this, simply remove this file --><!-- To find out more about CLS, visit https://web.dev/vitals/ --><link href="https://a.pub.network/worldometers-info/cls.css" rel="stylesheet"/><script data-cfasync="false" type="text/javascript">
  // must be 'var'
  var freestar = freestar || {};

  freestar.queue = freestar.queue || [];

  freestar.config = freestar.config || {};
  freestar.config.enabled_slots = [];

  freestar.initCallback = function () {
    // eslint-disable-next-line @typescript-eslint/no-unused-expressions
    freestar.config.enabled_slots.length === 0
      ? (freestar.initCallbackCalled = false)
      : freestar.newAdSlots(freestar.config.enabled_slots);
  };
</script><script async="" data-cfasync="false" src="https://a.pub.network/worldometers-info/pubfig.min.js"></script><meta content="en" property="og:locale"/><meta content="website" property="og:type"/><meta content="https://www.worldometers.info/world-population/population-by-country/" property="og:url"/><meta content="Worldometer" property="og:site_name"/><meta content="Population by Country (2025) - Worldometer" property="og:title"/><meta content="List of countries and dependencies in the world ranked by population, from the most populated. Growth rate, median age, fertility rate, area, density, population density, urbanization, urban population, share of world population." property="og:description"/><meta content="https://www.worldometers.info/img/worldometers-fb.jpg" property="og:image"/><link href="/favicon/favicon.ico" rel="shortcut icon" type="image/x-icon"/><link href="/favicon/apple-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/><link href="/favicon/apple-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/><link href="/favicon/apple-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/><link href="/favicon/apple-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/><link href="/favicon/apple-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/><link href="/favicon/apple-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/><link href="/favicon/apple-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/><link href="/favicon/apple-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/><link href="/favicon/apple-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/><link href="/favicon/android-icon-192x192.png" rel="icon" sizes="192x192" type="image/png"/><link href="/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/><link href="/favicon/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png"/><link href="/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/><link href="/favicon/manifest.json" rel="manifest"/><meta content="#ffffff" name="msapplication-TileColor"/><meta content="/favicon/ms-icon-144x144.png" name="msapplication-TileImage"/><meta content="#ffffff" name="theme-color"/><link href="https://fonts.googleapis.com" rel="preconnect"/><link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/><link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&amp;family=Roboto+Condensed:ital,wght@0,100..900;1,100..900&amp;display=swap" rel="stylesheet"/><meta content="List of countries and dependencies in the world ranked by population, from the most populated. Growth rate, median age, fertility rate, area, density, population density, urbanization, urban population, share of world population." name="description"/><script src="/_astro/layout-base.astro_astro_type_script_index_0_lang.GicbfbMM.js" type="module"></script><!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries --><!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]--><link href="/_astro/index.Dou_Uoxd.css" rel="stylesheet"/>
<style>/*! tailwindcss v4.1.17 | MIT License | https://tailwindcss.com */@layer properties{@supports (((-webkit-hyphens:none)) and (not (margin-trim:inline))) or ((-moz-orient:inline) and (not (color:rgb(from red r g b)))){*,:before,:after,::backdrop{--tw-border-style:solid}}}table.datatable tbody tr:nth-child(odd){background-color:var(--color-zinc-100,oklch(96.7% .001 286.375))}table.datatable:not(.datatable-table) thead th [data-sorting-icon]{display:none}table.datatable thead th[data-sortable=true]{cursor:pointer}table.datatable thead .datatable-sorter{cursor:pointer;justify-content:space-between;align-items:center;gap:calc(var(--spacing,.25rem)*1);width:100%;display:flex}table.datatable thead .datatable-sorter span{text-align:start}table.datatable :target td{background-color:var(--color-yellow-100,oklch(97.3% .071 103.193))}.datatable-wrapper .datatable-top{margin-bottom:calc(var(--spacing,.25rem)*3);align-items:flex-start;gap:calc(var(--spacing,.25rem)*1);flex-direction:column;display:flex}.datatable-wrapper .datatable-top .datatable-search{margin-inline-start:auto}.left-datatable-search .datatable-wrapper .datatable-top .datatable-search{margin:0}.datatable-wrapper .datatable-input,.datatable-wrapper .datatable-selector{border-radius:calc(var(--radius) - 4px);border-style:var(--tw-border-style);border-width:1px;border-color:var(--color-zinc-400,oklch(70.5% .015 286.067));padding-inline:calc(var(--spacing,.25rem)*2);padding-block:calc(var(--spacing,.25rem)*1.5);outline-color:var(--color-lime-500,oklch(76.8% .233 130.85))}.datatable-wrapper .datatable-input{justify-content:flex-end;min-width:16rem}@media(min-width:640px){.datatable-wrapper .datatable-top{flex-direction:row;align-items:center}}.datatable-wrapper .datatable-bottom{margin-top:calc(var(--spacing,.25rem)*3);justify-content:space-between;align-items:flex-start;gap:calc(var(--spacing,.25rem)*1);flex-direction:column;display:flex}@media(min-width:640px){.datatable-wrapper .datatable-bottom{flex-direction:row;align-items:center}}.datatable-wrapper .datatable-bottom .datatable-pagination-list{color:var(--color-zinc-500,oklch(55.2% .016 285.938));align-items:center;display:flex}.datatable-wrapper .datatable-bottom .datatable-pagination-list-item-link{border-block-style:var(--tw-border-style);border-block-width:1px;border-inline-end-style:var(--tw-border-style);border-inline-end-width:1px;border-color:var(--color-zinc-200,oklch(92% .004 286.32));padding-inline:calc(var(--spacing,.25rem)*3);padding-block:calc(var(--spacing,.25rem)*.5);align-items:center;display:flex}.datatable-wrapper .datatable-bottom .datatable-active{background-color:var(--color-zinc-100,oklch(96.7% .001 286.375))}.datatable-wrapper .datatable-bottom .datatable-hidden{cursor:not-allowed;opacity:.5}.datatable-wrapper .datatable-bottom .datatable-pagination-list-item:not(.datatable-active):not(.datatable-disabled):hover{cursor:pointer;background-color:var(--color-zinc-100,oklch(96.7% .001 286.375));text-decoration-line:underline}.datatable-wrapper .datatable-bottom .datatable-pagination-list-item:first-of-type .datatable-pagination-list-item-link{border-left-style:var(--tw-border-style);border-left-width:1px;border-start-start-radius:.25rem;border-end-start-radius:.25rem}.datatable-wrapper .datatable-bottom .datatable-pagination-list-item:last-of-type .datatable-pagination-list-item-link{border-start-end-radius:.25rem;border-end-end-radius:.25rem}.datatable-container{overflow-x:auto}@property --tw-border-style{syntax:"*";inherits:false;initial-value:solid}
@keyframes astroFadeInOut{0%{opacity:1}to{opacity:0}}@keyframes astroFadeIn{0%{opacity:0;mix-blend-mode:plus-lighter}to{opacity:1;mix-blend-mode:plus-lighter}}@keyframes astroFadeOut{0%{opacity:1;mix-blend-mode:plus-lighter}to{opacity:0;mix-blend-mode:plus-lighter}}@keyframes astroSlideFromRight{0%{transform:translate(100%)}}@keyframes astroSlideFromLeft{0%{transform:translate(-100%)}}@keyframes astroSlideToRight{to{transform:translate(100%)}}@keyframes astroSlideToLeft{to{transform:translate(-100%)}}@media(prefers-reduced-motion){::view-transition-group(*),::view-transition-old(*),::view-transition-new(*){animation:none!important}[data-astro-transition-scope]{animation:none!important}}
</style><script src="/_astro/page.DcbkM2AB.js" type="module"></script><style>[data-astro-transition-scope="astro-s7reefwf-2"] { view-transition-name: astro-s7reefwf-2; }@layer astro { ::view-transition-old(astro-s7reefwf-2) { animation: none; opacity: 0; mix-blend-mode: normal; }::view-transition-new(astro-s7reefwf-2) { animation: none; mix-blend-mode: normal; }::view-transition-group(astro-s7reefwf-2) { animation: none } }[data-astro-transition-fallback="old"] [data-astro-transition-scope="astro-s7reefwf-2"],
			[data-astro-transition-fallback="old"][data-astro-transition-scope="astro-s7reefwf-2"] { animation: none; mix-blend-mode: normal; }[data-astro-transition-fallback="new"] [data-astro-transition-scope="astro-s7reefwf-2"],
			[data-astro-transition-fallback="new"][data-astro-transition-scope="astro-s7reefwf-2"] { animation: none; mix-blend-mode: normal; }</style><style>[data-astro-transition-scope="astro-mbwfp7g5-3"] { view-transition-name: layout-header; }@layer astro { ::view-transition-old(layout-header) {
	animation-duration: 180ms;
	animation-timing-function: cubic-bezier(0.76, 0, 0.24, 1);
	animation-fill-mode: both;
	animation-name: astroFadeOut; }::view-transition-new(layout-header) {
	animation-duration: 180ms;
	animation-timing-function: cubic-bezier(0.76, 0, 0.24, 1);
	animation-fill-mode: both;
	animation-name: astroFadeIn; }[data-astro-transition=back]::view-transition-old(layout-header) {
	animation-duration: 180ms;
	animation-timing-function: cubic-bezier(0.76, 0, 0.24, 1);
	animation-fill-mode: both;
	animation-name: astroFadeOut; }[data-astro-transition=back]::view-transition-new(layout-header) {
	animation-duration: 180ms;
	animation-timing-function: cubic-bezier(0.76, 0, 0.24, 1);
	animation-fill-mode: both;
	animation-name: astroFadeIn; } }[data-astro-transition-fallback="old"] [data-astro-transition-scope="astro-mbwfp7g5-3"],
			[data-astro-transition-fallback="old"][data-astro-transition-scope="astro-mbwfp7g5-3"] {
	animation-duration: 180ms;
	animation-timing-function: cubic-bezier(0.76, 0, 0.24, 1);
	animation-fill-mode: both;
	animation-name: astroFadeOut; }[data-astro-transition-fallback="new"] [data-astro-transition-scope="astro-mbwfp7g5-3"],
			[data-astro-transition-fallback="new"][data-astro-transition-scope="astro-mbwfp7g5-3"] {
	animation-duration: 180ms;
	animation-timing-function: cubic-bezier(0.76, 0, 0.24, 1);
	animation-fill-mode: both;
	animation-name: astroFadeIn; }[data-astro-transition=back][data-astro-transition-fallback="old"] [data-astro-transition-scope="astro-mbwfp7g5-3"],
			[data-astro-transition=back][data-astro-transition-fallback="old"][data-astro-transition-scope="astro-mbwfp7g5-3"] {
	animation-duration: 180ms;
	animation-timing-function: cubic-bezier(0.76, 0, 0.24, 1);
	animation-fill-mode: both;
	animation-name: astroFadeOut; }[data-astro-transition=back][data-astro-transition-fallback="new"] [data-astro-transition-scope="astro-mbwfp7g5-3"],
			[data-astro-transition=back][data-astro-transition-fallback="new"][data-astro-transition-scope="astro-mbwfp7g5-3"] {
	animation-duration: 180ms;
	animation-timing-function: cubic-bezier(0.76, 0, 0.24, 1);
	animation-fill-mode: both;

In [145]:
table=soup.find('table')
table

<table class="datatable w-full border border-zinc-200" data-locale="en" data-options='{"searchable":true,"sortable":true,"defaultSort":"#","pageSize":false}' data-sort-col="0" data-sort-dir="asc" id=""> <thead> <tr> <th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true"> <span>#</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true"> <span>Country (or dependency)</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Population 2025</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Yearly Change</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Net Change</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Density (P/Km²)</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Land Area (Km²)</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Migrants (net)</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Fert. Rate</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Median Age</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Urban Pop %</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>World Share</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th> </tr> </thead> <tbody> <tr id="india"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 1 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-astro-reload="true" href="/world-population/india-population/"> India </a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="14638655250000" dir="ltr"> 1,463,865,525 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="89" dir="ltr"> 0.89% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="129297340000" dir="ltr"> 12,929,734 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="4923552" dir="ltr"> 492 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="29731900000" dir="ltr"> 2,973,190 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-4957530000" dir="ltr"> −495,753 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="19430" dir="ltr"> 1.94 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="288290" dir="ltr"> 28.8 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="3708" dir="ltr"> 37.1% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1778" dir="ltr"> 17.78% </td> </tr><tr id="china"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 2 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-astro-reload="true" href="/world-population/china-population/"> China </a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="14160960940000" dir="ltr"> 1,416,096,094 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-23" dir="ltr"> −0.23% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-32251840000" dir="ltr"> −3,225,184 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1508377" dir="ltr"> 151 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="93882110000" dir="ltr"> 9,388,211 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-2681260000" dir="ltr"> −268,126 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="10210" dir="ltr"> 1.02 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="401080" dir="ltr"> 40.1 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="6755" dir="ltr"> 67.5% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1720" dir="ltr"> 17.20% </td> </tr><tr id="us"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 3 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-astro-reload="true" href="/world-population/us-population/"> United States </a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="3472758070000" dir="ltr"> 347,275,807 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="54" dir="ltr"> 0.54% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="18492360000" dir="ltr"> 1,849,236 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="379643" dir="ltr"> 38 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="91474200000" dir="ltr"> 9,147,420 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="12306630000" dir="ltr"> 1,230,663 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="16230" dir="ltr"> 1.62 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="385010" dir="ltr"> 38.5 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="8276" dir="ltr"> 82.8% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="422" dir="ltr"> 4.22% </td> </tr><tr id="indonesia"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 4 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-astro-reload="true" href="/world-population/indonesia-population/"> Indonesia </a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="2857212360000" dir="ltr"> 285,721,236 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="79" dir="ltr"> 0.79% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="22333050000" dir="ltr"> 2,233,305 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1577202" dir="ltr"> 158 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="18115700000" dir="ltr"> 1,811,570 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-395090000" dir="ltr"> −39,509 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="20960" dir="ltr"> 2.1 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="303790" dir="ltr"> 30.4 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="5963" dir="ltr"> 59.6% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="347" dir="ltr"> 3.47% </td> </tr><tr id="pakistan"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 5 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-astro-reload="true" href="/world-population/pakistan-population/"> Pakistan </a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="2552195540000" dir="ltr"> 255,219,554 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="157" dir="ltr"> 1.57% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="39503900000" dir="ltr"> 3,950,390 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="3310756" dir="ltr"> 331 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="7708800000" dir="ltr"> 770,880 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-12353360000" dir="ltr"> −1,235,336 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="34950" dir="ltr"> 3.5 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="206030" dir="ltr"> 20.6 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="3439" dir="ltr"> 34.4% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="310" dir="ltr"> 3.10% </td> </tr><tr id="nigeria"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 6 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-astro-reload="true" href="/world-population/nigeria-population/"> Nigeria </a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="2375277820000" dir="ltr"> 237,527,782 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="208" dir="ltr"> 2.08% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="48483040000" dir="ltr"> 4,848,304 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="2607989" dir="ltr"> 261 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="9107700000" dir="ltr"> 910,770 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-152580000" dir="ltr"> −15,258 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="42970" dir="ltr"> 4.3 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="181420" dir="ltr"> 18.1 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="5486" dir="ltr"> 54.9% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="289" dir="ltr"> 2.89% </td> </tr><tr id="brazil"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 7 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-astro-reload="true" href="/world-population/brazil-population/"> Brazil </a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="2128124050000" dir="ltr"> 212,812,405 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="38" dir="ltr"> 0.38% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="8138320000" dir="ltr"> 813,832 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="254617" dir="ltr"> 25 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="83581400000" dir="ltr"> 8,358,140 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-2172830000" dir="ltr"> −217,283 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="16000" dir="ltr"> 1.6 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="348180" dir="ltr"> 34.8 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="9137" dir="ltr"> 91.4% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="259" dir="ltr"> 2.59% </td> </tr><tr id="bangladesh"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 8 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-astro-reload="true" href="/world-population/bangladesh-population/"> Bangladesh </a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="1756868990000" dir="ltr"> 175,686,899 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="122" dir="ltr"> 1.22% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="21245350000" dir="ltr"> 2,124,535 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="13496727" dir="ltr"> 1,350 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1301700000" dir="ltr"> 130,170 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-4021000000" dir="ltr"> −402,100 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="21140" dir="ltr"> 2.11 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="259770" dir="ltr"> 26 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="4260" dir="ltr"> 42.6% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="213" dir="ltr"> 2.13% </td> </tr><tr id="russia"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 9 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-astro-reload="true" href="/world-population/russia-population/"> Russia </a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="1439973930000" dir="ltr"> 143,997,393 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-57" dir="ltr"> −0.57% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-8230300000" dir="ltr"> −823,030 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="87927" dir="ltr"> 9 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="163768700000" dir="ltr"> 16,376,870 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-2518220000" dir="ltr"> −251,822 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="14650" dir="ltr"> 1.47 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="402970" dir="ltr"> 40.3 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="7504" dir="ltr"> 75% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="175" dir="ltr"> 1.75% </td> </tr><tr id="ethiopia"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 10 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-astro-reload="true" href="/world-population/ethiopia-population/"> Ethiopia </a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="1354720510000" dir="ltr"> 135,472,051 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="258" dir="ltr"> 2.58% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="34122840000" dir="ltr"> 3,412,284 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1354721" dir="ltr"> 135 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="10000000000" dir="ltr"> 1,000,000 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="240540000" dir="ltr"> 24,054 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="38060" dir="ltr"> 3.81 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-o

In [146]:
rows=soup.find_all('tr')
rows

[<tr> <th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true"> <span>#</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true"> <span>Country (or dependency)</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Population 2025</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Yearly Change</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Net Change</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Density (P/Km²)</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Land Area (Km²)</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Migrants (net)</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Fert. Rate</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Median Age</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>Urban Pop %</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th><th class="px-2 border-e border-zinc-200 align-middle text-center font-semibold border-b-3 py-1" data-sortable="true" data-type="number"> <span>World Share</span> <svg aria-hidden="true" class="size-4 shrink-0" data-sorting-icon="true" fill="none" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="m8 15 4 4 4-4m0-6-4-4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path> </svg> </th> </tr>,
 <tr id="india"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 1 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-astro-reload="true" href="/world-population/india-population/"> India </a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="14638655250000" dir="ltr"> 1,463,865,525 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="89" dir="ltr"> 0.89% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="129297340000" dir="ltr"> 12,929,734 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="4923552" dir="ltr"> 492 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="29731900000" dir="ltr"> 2,973,190 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-4957530000" dir="ltr"> −495,753 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="19430" dir="ltr"> 1.94 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="288290" dir="ltr"> 28.8 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="3708" dir="ltr"> 37.1% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1778" dir="ltr"> 17.78% </td> </tr>,
 <tr id="china"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 2 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-astro-reload="true" href="/world-population/china-population/"> China </a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="14160960940000" dir="ltr"> 1,416,096,094 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-23" dir="ltr"> −0.23% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-32251840000" dir="ltr"> −3,225,184 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1508377" dir="ltr"> 151 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="93882110000" dir="ltr"> 9,388,211 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-2681260000" dir="ltr"> −268,126 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="10210" dir="ltr"> 1.02 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="401080" dir="ltr"> 40.1 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="6755" dir="ltr"> 67.5% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1720" dir="ltr"> 17.20% </td> </tr>,
 <tr id="us"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 3 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-astro-reload="true" href="/world-population/us-population/"> United States </a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="3472758070000" dir="ltr"> 347,275,807 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="54" dir="ltr"> 0.54% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="18492360000" dir="ltr"> 1,849,236 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="379643" dir="ltr"> 38 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="91474200000" dir="ltr"> 9,147,420 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="12306630000" dir="ltr"> 1,230,663 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="16230" dir="ltr"> 1.62 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="385010" dir="ltr"> 38.5 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="8276" dir="ltr"> 82.8% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="422" dir="ltr"> 4.22% </td> </tr>,
 <tr id="indonesia"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 4 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-astro-reload="true" href="/world-population/indonesia-population/"> Indonesia </a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="2857212360000" dir="ltr"> 285,721,236 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="79" dir="ltr"> 0.79% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="22333050000" dir="ltr"> 2,233,305 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1577202" dir="ltr"> 158 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="18115700000" dir="ltr"> 1,811,570 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-395090000" dir="ltr"> −39,509 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="20960" dir="ltr"> 2.1 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="303790" dir="ltr"> 30.4 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="5963" dir="ltr"> 59.6% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="347" dir="ltr"> 3.47% </td> </tr>,
 <tr id="pakistan"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 5 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-astro-reload="true" href="/world-population/pakistan-population/"> Pakistan </a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="2552195540000" dir="ltr"> 255,219,554 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="157" dir="ltr"> 1.57% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="39503900000" dir="ltr"> 3,950,390 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="3310756" dir="ltr"> 331 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="7708800000" dir="ltr"> 770,880 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-12353360000" dir="ltr"> −1,235,336 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="34950" dir="ltr"> 3.5 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="206030" dir="ltr"> 20.6 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="3439" dir="ltr"> 34.4% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="310" dir="ltr"> 3.10% </td> </tr>,
 <tr id="nigeria"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 6 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-astro-reload="true" href="/world-population/nigeria-population/"> Nigeria </a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="2375277820000" dir="ltr"> 237,527,782 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="208" dir="ltr"> 2.08% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="48483040000" dir="ltr"> 4,848,304 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="2607989" dir="ltr"> 261 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="9107700000" dir="ltr"> 910,770 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-152580000" dir="ltr"> −15,258 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="42970" dir="ltr"> 4.3 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="181420" dir="ltr"> 18.1 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="5486" dir="ltr"> 54.9% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="289" dir="ltr"> 2.89% </td> </tr>,
 <tr id="brazil"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 7 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-astro-reload="true" href="/world-population/brazil-population/"> Brazil </a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="2128124050000" dir="ltr"> 212,812,405 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="38" dir="ltr"> 0.38% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="8138320000" dir="ltr"> 813,832 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="254617" dir="ltr"> 25 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="83581400000" dir="ltr"> 8,358,140 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-2172830000" dir="ltr"> −217,283 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="16000" dir="ltr"> 1.6 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="348180" dir="ltr"> 34.8 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="9137" dir="ltr"> 91.4% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="259" dir="ltr"> 2.59% </td> </tr>,
 <tr id="bangladesh"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 8 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-astro-reload="true" href="/world-population/bangladesh-population/"> Bangladesh </a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="1756868990000" dir="ltr"> 175,686,899 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="122" dir="ltr"> 1.22% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="21245350000" dir="ltr"> 2,124,535 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="13496727" dir="ltr"> 1,350 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="1301700000" dir="ltr"> 130,170 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-4021000000" dir="ltr"> −402,100 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="21140" dir="ltr"> 2.11 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="259770" dir="ltr"> 26 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="4260" dir="ltr"> 42.6% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="213" dir="ltr"> 2.13% </td> </tr>,
 <tr id="russia"> <td class="px-2 border-e border-zinc-200 py-1.5 border-b text-start"> 9 </td><td class="px-2 border-e border-zinc-200 py-1.5 border-b font-bold text-start"> <a class="transition-all duration-200 text-lime-600 hover:text-lime-500" data-astro-reload="true" href="/world-population/russia-population/"> Russia </a> </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b font-bold" data-order="1439973930000" dir="ltr"> 143,997,393 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-57" dir="ltr"> −0.57% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-8230300000" dir="ltr"> −823,030 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="87927" dir="ltr"> 9 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="163768700000" dir="ltr"> 16,376,870 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="-2518220000" dir="ltr"> −251,822 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="14650" dir="ltr"> 1.47 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="402970" dir="ltr"> 40.3 </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="7504" dir="ltr"> 75% </td><td class="px-2 border-e border-zinc-200 text-end py-1.5 border-b" data-order="175" dir="ltr"> 1.75% </td> </tr>,

In [147]:
population_count = []

for row in rows:   # skip header
    cols = row.find_all('td')
    pop=[p.text for p in cols]
    population_count.append(pop)
population_count

[[],
 [' 1 ',
  '  India  ',
  ' 1,463,865,525 ',
  ' 0.89% ',
  ' 12,929,734 ',
  ' 492 ',
  ' 2,973,190 ',
  ' −495,753 ',
  ' 1.94 ',
  ' 28.8 ',
  ' 37.1% ',
  ' 17.78% '],
 [' 2 ',
  '  China  ',
  ' 1,416,096,094 ',
  ' −0.23% ',
  ' −3,225,184 ',
  ' 151 ',
  ' 9,388,211 ',
  ' −268,126 ',
  ' 1.02 ',
  ' 40.1 ',
  ' 67.5% ',
  ' 17.20% '],
 [' 3 ',
  '  United States  ',
  ' 347,275,807 ',
  ' 0.54% ',
  ' 1,849,236 ',
  ' 38 ',
  ' 9,147,420 ',
  ' 1,230,663 ',
  ' 1.62 ',
  ' 38.5 ',
  ' 82.8% ',
  ' 4.22% '],
 [' 4 ',
  '  Indonesia  ',
  ' 285,721,236 ',
  ' 0.79% ',
  ' 2,233,305 ',
  ' 158 ',
  ' 1,811,570 ',
  ' −39,509 ',
  ' 2.1 ',
  ' 30.4 ',
  ' 59.6% ',
  ' 3.47% '],
 [' 5 ',
  '  Pakistan  ',
  ' 255,219,554 ',
  ' 1.57% ',
  ' 3,950,390 ',
  ' 331 ',
  ' 770,880 ',
  ' −1,235,336 ',
  ' 3.5 ',
  ' 20.6 ',
  ' 34.4% ',
  ' 3.10% '],
 [' 6 ',
  '  Nigeria  ',
  ' 237,527,782 ',
  ' 2.08% ',
  ' 4,848,304 ',
  ' 261 ',
  ' 910,770 ',
  ' −15,258 ',
  ' 4.3 ',
  ' 18.1 ',
  ' 54.9% ',
  ' 2.89% '],
 [' 7 ',
  '  Brazil  ',
  ' 212,812,405 ',
  ' 0.38% ',
  ' 813,832 ',
  ' 25 ',
  ' 8,358,140 ',
  ' −217,283 ',
  ' 1.6 ',
  ' 34.8 ',
  ' 91.4% ',
  ' 2.59% '],
 [' 8 ',
  '  Bangladesh  ',
  ' 175,686,899 ',
  ' 1.22% ',
  ' 2,124,535 ',
  ' 1,350 ',
  ' 130,170 ',
  ' −402,100 ',
  ' 2.11 ',
  ' 26 ',
  ' 42.6% ',
  ' 2.13% '],
 [' 9 ',
  '  Russia  ',
  ' 143,997,393 ',
  ' −0.57% ',
  ' −823,030 ',
  ' 9 ',
  ' 16,376,870 ',
  ' −251,822 ',
  ' 1.47 ',
  ' 40.3 ',
  ' 75% ',
  ' 1.75% '],
 [' 10 ',
  '  Ethiopia  ',
  ' 135,472,051 ',
  ' 2.58% ',
  ' 3,412,284 ',
  ' 135 ',
  ' 1,000,000 ',
  ' 24,054 ',
  ' 3.81 ',
  ' 19.1 ',
  ' 22.5% ',
  ' 1.65% '],
 [' 11 ',
  '  Mexico  ',
  ' 131,946,900 ',
  ' 0.83% ',
  ' 1,085,893 ',
  ' 68 ',
  ' 1,943,950 ',
  ' −108,037 ',
  ' 1.87 ',
  ' 29.6 ',
  ' 87.9% ',
  ' 1.60% '],
 [' 12 ',
  '  Japan  ',
  ' 123,103,479 ',
  ' −0.52% ',
  ' −649,562 ',
  ' 338 ',
  ' 364,555 ',
  ' 140,579 ',
  ' 1.23 ',
  ' 49.8 ',
  ' 93.1% ',
  ' 1.50% '],
 [' 13 ',
  '  Egypt  ',
  ' 118,365,995 ',
  ' 1.57% ',
  ' 1,827,737 ',
  ' 119 ',
  ' 995,450 ',
  ' −57,305 ',
  ' 2.71 ',
  ' 24.5 ',
  ' 40.9% ',
  ' 1.44% '],
 [' 14 ',
  '  Philippines  ',
  ' 116,786,962 ',
  ' 0.81% ',
  ' 943,292 ',
  ' 392 ',
  ' 298,170 ',
  ' −149,315 ',
  ' 1.88 ',
  ' 26.1 ',
  ' 49.3% ',
  ' 1.42% '],
 [' 15 ',
  '  DR Congo  ',
  ' 112,832,473 ',
  ' 3.25% ',
  ' 3,556,208 ',
  ' 50 ',
  ' 2,267,050 ',
  ' −27,309 ',
  ' 5.9 ',
  ' 15.8 ',
  ' 45% ',
  ' 1.37% '],
 [' 16 ',
  '  Vietnam  ',
  ' 101,598,527 ',
  ' 0.6% ',
  ' 610,841 ',
  ' 328 ',
  ' 310,070 ',
  ' −48,171 ',
  ' 1.88 ',
  ' 33.4 ',
  ' 41.4% ',
  ' 1.23% '],
 [' 17 ',
  '  Iran  ',
  ' 92,417,681 ',
  ' 0.93% ',
  ' 849,943 ',
  ' 57 ',
  ' 1,628,550 ',
  ' 116,786 ',
  ' 1.67 ',
  ' 34 ',
  ' 73.3% ',
  ' 1.12% '],
 [' 18 ',
  '  Turkey  ',
  ' 87,685,426 ',
  ' 0.24% ',
  ' 211,621 ',
  ' 114 ',
  ' 769,630 ',
  ' −258,205 ',
  ' 1.62 ',
  ' 33.5 ',
  ' 76.9% ',
  ' 1.07% '],
 [' 19 ',
  '  Germany  ',
  ' 84,075,075 ',
  ' −0.56% ',
  ' −477,167 ',
  ' 241 ',
  ' 348,560 ',
  ' −334,072 ',
  ' 1.46 ',
  ' 45.5 ',
  ' 76.5% ',
  ' 1.02% '],
 [' 20 ',
  '  Thailand  ',
  ' 71,619,863 ',
  ' −0.07% ',
  ' −48,148 ',
  ' 140 ',
  ' 510,890 ',
  ' 27,509 ',
  ' 1.2 ',
  ' 40.6 ',
  ' 53.5% ',
  ' 0.87% '],
 [' 21 ',
  '  Tanzania  ',
  ' 70,545,865 ',
  ' 2.9% ',
  ' 1,985,708 ',
  ' 80 ',
  ' 885,800 ',
  ' −12,730 ',
  ' 4.47 ',
  ' 17.5 ',
  ' 40% ',
  ' 0.86% '],
 [' 22 ',
  '  United Kingdom  ',
  ' 69,551,332 ',
  ' 0.6% ',
  ' 413,140 ',
  ' 287 ',
  ' 241,930 ',
  ' 389,911 ',
  ' 1.54 ',
  ' 40.1 ',
  ' 84.5% ',
  ' 0.84% '],
 [' 23 ',
  '  France  ',
  ' 66,650,804 ',
  ' 0.15% ',
  ' 102,274 ',
  ' 122 ',
  ' 547,557 ',
  ' 91,737 ',
  ' 1.64 ',
  ' 42.3 ',
  ' 82.5% ',
  ' 0.81% '],
 [' 24 ',
  '  South Africa  ',
  ' 64,747,319 ',
  ' 1.16% ',
  ' 740,132 ',
  ' 53 ',
  ' 1,213,090 ',
  ' 146,370 ',
  ' 2.19 ',
  ' 28.7 ',
  ' 66.6% ',
  ' 0.79% '],
 [' 25 ',
  '  Italy  ',
  ' 59,146,260 ',
  ' −0.33% ',
  ' −196,607 ',
  ' 201 ',
  ' 294,140 ',
  ' 75,448 ',
  ' 1.21 ',
  ' 48.2 ',
  ' 72% ',
  ' 0.72% '],
 [' 26 ',
  '  Kenya  ',
  ' 57,532,493 ',
  ' 1.95% ',
  ' 1,099,549 ',
  ' 101 ',
  ' 569,140 ',
  ' −27,330 ',
  ' 3.12 ',
  ' 20 ',
  ' 31.9% ',
  ' 0.70% '],
 [' 27 ',
  '  Myanmar  ',
  ' 54,850,648 ',
  ' 0.64% ',
  ' 350,557 ',
  ' 84 ',
  ' 653,290 ',
  ' −39,661 ',
  ' 2.08 ',
  ' 30.1 ',
  ' 34.1% ',
  ' 0.67% '],
 [' 28 ',
  '  Colombia  ',
  ' 53,425,635 ',
  ' 1.02% ',
  ' 539,272 ',
  ' 48 ',
  ' 1,109,500 ',
  ' 129,139 ',
  ' 1.62 ',
  ' 32.5 ',
  ' 80.5% ',
  ' 0.65% '],
 [' 29 ',
  '  South Korea  ',
  ' 51,667,029 ',
  ' −0.1% ',
  ' −50,561 ',
  ' 531 ',
  ' 97,230 ',
  ' 65,731 ',
  ' 0.75 ',
  ' 45.6 ',
  ' 82.4% ',
  ' 0.63% '],
 [' 30 ',
  '  Sudan  ',
  ' 51,662,147 ',
  ' 2.4% ',
  ' 1,213,184 ',
  ' 29 ',
  ' 1,765,048 ',
  ' 291,469 ',
  ' 4.19 ',
  ' 18.5 ',
  ' 35.3% ',
  ' 0.63% '],
 [' 31 ',
  '  Uganda  ',
  ' 51,384,894 ',
  ' 2.74% ',
  ' 1,369,802 ',
  ' 257 ',
  ' 199,810 ',
  ' −119,059 ',
  ' 4.06 ',
  ' 16.9 ',
  ' 30% ',
  ' 0.62% '],
 [' 32 ',
  '  Spain  ',
  ' 47,889,958 ',
  ' −0.04% ',
  ' −20,568 ',
  ' 96 ',
  ' 498,800 ',
  ' 96,630 ',
  ' 1.23 ',
  ' 45.9 ',
  ' 79.3% ',
  ' 0.58% '],
 [' 33 ',
  '  Algeria  ',
  ' 47,435,312 ',
  ' 1.33% ',
  ' 621,004 ',
  ' 20 ',
  ' 2,381,740 ',
  ' −27,531 ',
  ' 2.67 ',
  ' 28.6 ',
  ' 74.4% ',
  ' 0.58% '],
 [' 34 ',
  '  Iraq  ',
  ' 47,020,774 ',
  ' 2.13% ',
  ' 978,759 ',
  ' 108 ',
  ' 434,320 ',
  ' −1,064 ',
  ' 3.17 ',
  ' 20.8 ',
  ' 72.4% ',
  ' 0.57% '],
 [' 35 ',
  '  Argentina  ',
  ' 45,851,378 ',
  ' 0.34% ',
  ' 155,219 ',
  ' 17 ',
  ' 2,736,690 ',
  ' 2,859 ',
  ' 1.5 ',
  ' 32.9 ',
  ' 96% ',
  ' 0.56% '],
 [' 36 ',
  '  Afghanistan  ',
  ' 43,844,111 ',
  ' 2.81% ',
  ' 1,196,619 ',
  ' 67 ',
  ' 652,860 ',
  ' −74,404 ',
  ' 4.66 ',
  ' 17.3 ',
  ' 26.7% ',
  ' 0.53% '],
 [' 37 ',
  '  Yemen  ',
  ' 41,773,878 ',
  ' 2.93% ',
  ' 1,190,714 ',
  ' 79 ',
  ' 527,970 ',
  ' −16,291 ',
  ' 4.41 ',
  ' 18.4 ',
  ' 33% ',
  ' 0.51% '],
 [' 38 ',
  '  Canada  ',
  ' 40,126,723 ',
  ' 0.97% ',
  ' 384,293 ',
  ' 4 ',
  ' 9,093,510 ',
  ' 326,204 ',
  ' 1.33 ',
  ' 40.6 ',
  ' 80.2% ',
  ' 0.49% '],
 [' 39 ',
  '  Angola  ',
  ' 39,040,039 ',
  ' 3.05% ',
  ' 1,154,190 ',
  ' 31 ',
  ' 1,246,700 ',
  ' −3,524 ',
  ' 4.95 ',
  ' 16.6 ',
  ' 68.8% ',
  ' 0.47% '],
 [' 40 ',
  '  Ukraine  ',
  ' 38,980,376 ',
  ' 2.96% ',
  ' 1,120,155 ',
  ' 67 ',
  ' 579,320 ',
  ' 1,702,358 ',
  ' 1 ',
  ' 41.8 ',
  ' 76.8% ',
  ' 0.47% '],
 [' 41 ',
  '  Morocco  ',
  ' 38,430,770 ',
  ' 0.92% ',
  ' 349,597 ',
  ' 86 ',
  ' 446,300 ',
  ' −56,254 ',
  ' 2.18 ',
  ' 29.8 ',
  ' 67.3% ',
  ' 0.47% '],
 [' 42 ',
  '  Poland  ',
  ' 38,140,910 ',
  ' −1.03% ',
  ' −398,291 ',
  ' 125 ',
  ' 306,230 ',
  ' −330,820 ',
  ' 1.31 ',
  ' 42.5 ',
  ' 59.2% ',
  ' 0.46% '],
 [' 43 ',
  '  Uzbekistan  ',
  ' 37,053,428 ',
  ' 1.9% ',
  ' 691,569 ',
  ' 87 ',
  ' 425,400 ',
  ' −6,987 ',
  ' 3.45 ',
  ' 27 ',
  ' 48.1% ',
  ' 0.45% '],
 [' 44 ',
  '  Malaysia  ',
  ' 35,977,838 ',
  ' 1.18% ',
  ' 420,165 ',
  ' 110 ',
  ' 328,550 ',
  ' 166,615 ',
  ' 1.53 ',
  ' 31 ',
  ' 77.4% ',
  ' 0.44% '],
 [' 45 ',
  '  Mozambique  ',
  ' 35,631,653 ',
  ' 2.89% ',
  ' 999,887 ',
  ' 45 ',
  ' 786,380 ',
  ' −65,573 ',
  ' 4.62 ',
  ' 16.5 ',
  ' 41.6% ',
  ' 0.43% '],
 [' 46 ',
  '  Ghana  ',
  ' 35,064,272 ',
  ' 1.85% ',
  ' 636,858 ',
  ' 154 ',
  ' 227,540 ',
  ' −17,079 ',
  ' 3.3 ',
  ' 21.3 ',
  ' 58.6% ',
  ' 0.43% '],
 [' 47 ',
  '  Peru  ',
  ' 34,576,665 ',
  ' 1.05% ',
  ' 358,817 ',
  ' 27 ',
  ' 1,280,000 ',
  ' 11,931 ',
  ' 1.94 ',
  ' 30.2 ',
  ' 80.6% ',
  ' 0.42% '],
 [' 48 ',
  '  Saudi Arabia  ',
  ' 34,566,328 ',
  ' 1.78% ',
  ' 603,571 ',
  ' 16 ',
  ' 2,149,690 ',
  ' 119,738 ',
  ' 2.29 ',
  ' 29.6 ',
  ' 92.1% ',
  ' 0.42% '],
 [' 49 ',
  '  Madagascar  ',
  ' 32,740,678 ',
  ' 2.43% ',
  ' 775,722 ',
  ' 56 ',
  ' 581,795 ',
  ' −2,227 ',
  ' 3.85 ',
  ' 19.2 ',
  ' 40.3% ',
  ' 0.40% '],
 [' 50 ',
  "  Côte d'Ivoire  ",
  ' 32,711,547 ',
  ' 2.43% ',
  ' 777,317 ',
  ' 103 ',
  ' 318,000 ',
  ' 11,305 ',
  ' 4.17 ',
  ' 18.3 ',
  ' 49% ',
  ' 0.40% '],
 [' 51 ',
  '  Cameroon  ',
  ' 29,879,337 ',
  ' 2.59% ',
  ' 755,593 ',
  ' 63 ',
  ' 472,710 ',
  ' −15,379 ',
  ' 4.18 ',
  ' 18 ',
  ' 59.4% ',
  ' 0.36% '],
 [' 52 ',
  '  Nepal  ',
  ' 29,618,118 ',
  ' −0.11% ',
  ' −32,936 ',
  ' 207 ',
  ' 143,350 ',
  ' −364,699 ',
  ' 1.94 ',
  ' 25.3 ',
  ' 24.5% ',
  ' 0.36% '],
 [' 53 ',
  '  Venezuela  ',
  ' 28,516,896 ',
  ' 0.39% ',
  ' 111,353 ',
  ' 32 ',
  ' 882,050 ',
  ' −100,467 ',
  ' 2.06 ',
  ' 29.4 ',
  ' ',
  ' 0.35% '],
 [' 54 ',
  '  Niger  ',
  ' 27,917,831 ',
  ' 3.28% ',
  ' 885,419 ',
  ' 22 ',
  ' 1,266,700 ',
  ' −7,704 ',
  ' 5.79 ',
  ' 15.6 ',
  ' 18.2% ',
  ' 0.34% '],
 [' 55 ',
  '  Australia  ',
  ' 26,974,026 ',
  ' 0.98% ',
  ' 260,821 ',
  ' 4 ',
  ' 7,682,300 ',
  ' 137,109 ',
  ' 1.64 ',
  ' 38.3 ',
  ' 86.5% ',
  ' 0.33% '],
 [' 56 ',
  '  North Korea  ',
  ' 26,571,036 ',
  ' 0.27% ',
  ' 72,213 ',
  ' 221 ',
  ' 120,410 ',
  ' −2,787 ',
  ' 1.77 ',
  ' 36.5 ',
  ' 63.3% ',
  ' 0.32% '],
 [' 57 ',
  '  Syria  ',
  ' 25,620,427 ',
  ' 3.84% ',
  ' 947,667 ',
  ' 140 ',
  ' 183,630 ',
  ' 421,693 ',
  ' 2.66 ',
  ' 23.3 ',
  ' 53.6% ',
  ' 0.31% '],
 [' 58 ',
  '  Mali  ',
  ' 25,198,821 ',
  ' 2.94% ',
  ' 720,226 ',
  ' 21 ',
  ' 1,220,190 ',
  ' −48,019 ',
  ' 5.42 ',
  ' 15.7 ',
  ' 44.4% ',
  ' 0.31% '],
 [' 59 ',
  '  Burkina Faso  ',
  ' 24,074,580 ',
  ' 2.23% ',
  ' 525,799 ',
  ' 88 ',
  ' 273,600 ',
  ' −27,130 ',
  ' 4 ',
  ' 17.7 ',
  ' 33.7% ',
  ' 0.29% '],
 [' 60 ',
  '  Sri Lanka  ',
  ' 23,229,470 ',
  ' 0.54% ',
  ' 125,905 ',
  ' 370 ',
  ' 62,710 ',
  ' −30,724 ',
  ' 1.94 ',
  ' 33.3 ',
  ' 18.1% ',
  ' 0.28% '],
 [' 61 ',
  '  Taiwan  ',
  ' 23,112,793 ',
  ' −0.44% ',
  ' −101,169 ',
  ' 653 ',
  ' 35,410 ',
  ' −20,947 ',
  ' 0.86 ',
  ' 44.8 ',
  ' 84% ',
  ' 0.28% '],
 [' 62 ',
  '  Malawi  ',
  ' 22,216,120 ',
  ' 2.59% ',
  ' 560,834 ',
  ' 236 ',
  ' 94,280 ',
  ' −5,628 ',
  ' 3.53 ',
  ' 18.1 ',
  ' 19.8% ',
  ' 0.27% '],
 [' 63 ',
  '  Zambia  ',
  ' 21,913,874 ',
  ' 2.81% ',
  ' 598,918 ',
  ' 29 ',
  ' 743,390 ',
  ' 6,562 ',
  ' 3.97 ',
  ' 17.9 ',
  ' 46.8% ',
  ' 0.27% '],
 [' 64 ',
  '  Chad  ',
  ' 21,003,705 ',
  ' 3.47% ',
  ' 704,582 ',
  ' 17 ',
  ' 1,259,200 ',
  ' −123,104 ',
  ' 5.94 ',
  ' 15.8 ',
  ' 22.4% ',
  ' 0.26% '],
 [' 65 ',
  '  Kazakhstan  ',
  ' 20,843,754 ',
  ' 1.22% ',
  ' 251,183 ',
  ' 8 ',
  ' 2,699,700 ',
  ' −8,834 ',
  ' 2.95 ',
  ' 29.7 ',
  ' 55.1% ',
  ' 0.25% '],
 [' 66 ',
  '  Chile  ',
  ' 19,859,921 ',
  ' 0.48% ',
  ' 95,150 ',
  ' 27 ',
  ' 743,532 ',
  ' 51,712 ',
  ' 1.13 ',
  ' 36.9 ',
  ' 84.8% ',
  ' 0.24% '],
 [' 67 ',
  '  Somalia  ',
  ' 19,654,739 ',
  ' 3.4% ',
  ' 645,588 ',
  ' 31 ',
  ' 627,340 ',
  ' 12,077 ',
  ' 5.91 ',
  ' 15.6 ',
  ' 46.6% ',
  ' 0.24% '],
 [' 68 ',
  '  Senegal  ',
  ' 18,931,966 ',
  ' 2.32% ',
  ' 429,982 ',
  ' 98 ',
  ' 192,530 ',
  ' −12,636 ',
  ' 3.71 ',
  ' 19.6 ',
  ' 52.3% ',
  ' 0.23% '],
 [' 69 ',
  '  Romania  ',
  ' 18,908,650 ',
  ' −0.56% ',
  ' −106,438 ',
  ' 82 ',
  ' 230,170 ',
  ' −29,041 ',
  ' 1.71 ',
  ' 43.2 ',
  ' 55.2% ',
  ' 0.23% '],
 [' 70 ',
  '  Guatemala  ',
  ' 18,687,881 ',
  ' 1.53% ',
  ' 281,522 ',
  ' 174 ',
  ' 107,160 ',
  ' −7,959 ',
  ' 2.26 ',
  ' 23.4 ',
  ' 56.6% ',
  ' 0.23% '],
 [' 71 ',
  '  Netherlands  ',
  ' 18,346,819 ',
  ' 0.65% ',
  ' 118,077 ',
  ' 544 ',
  ' 33,720 ',
  ' 104,681 ',
  ' 1.44 ',
  ' 41.5 ',
  ' 88.9% ',
  ' 0.22% '],
 [' 72 ',
  '  Ecuador  ',
  ' 18,289,896 ',
  ' 0.85% ',
  ' 154,418 ',
  ' 74 ',
  ' 248,360 ',
  ' −17,219 ',
  ' 1.79 ',
  ' 29.3 ',
  ' 66% ',
  ' 0.22% '],
 [' 73 ',
  '  Cambodia  ',
  ' 17,847,982 ',
  ' 1.19% ',
  ' 209,181 ',
  ' 101 ',
  ' 176,520 ',
  ' −31,469 ',
  ' 2.51 ',
  ' 26.2 ',
  ' 26.5% ',
  ' 0.22% '],
 [' 74 ',
  '  Zimbabwe  ',
  ' 16,950,795 ',
  ' 1.9% ',
  ' 316,422 ',
  ' 44 ',
  ' 386,850 ',
  ' −54,555 ',
  ' 3.62 ',
  ' 18.1 ',
  ' 37.9% ',
  ' 0.21% '],
 [' 75 ',
  '  Guinea  ',
  ' 15,099,727 ',
  ' 2.34% ',
  ' 344,942 ',
  ' 61 ',
  ' 245,720 ',
  ' −16,282 ',
  ' 4.04 ',
  ' 18.3 ',
  ' 40.3% ',
  ' 0.18% '],
 [' 76 ',
  '  Benin  ',
  ' 14,814,460 ',
  ' 2.43% ',
  ' 351,736 ',
  ' 131 ',
  ' 112,760 ',
  ' −7,847 ',
  ' 4.42 ',
  ' 18 ',
  ' 47.8% ',
  ' 0.18% '],
 [' 77 ',
  '  Rwanda  ',
  ' 14,569,341 ',
  ' 2.19% ',
  ' 312,774 ',
  ' 591 ',
  ' 24,670 ',
  ' 6,282 ',
  ' 3.59 ',
  ' 19.9 ',
  ' 18.3% ',
  ' 0.18% '],
 [' 78 ',
  '  Burundi  ',
  ' 14,390,003 ',
  ' 2.44% ',
  ' 342,217 ',
  ' 560 ',
  ' 25,680 ',
  ' −34,727 ',
  ' 4.67 ',
  ' 16.4 ',
  ' 14.9% ',
  ' 0.17% '],
 [' 79 ',
  '  Bolivia  ',
  ' 12,581,843 ',
  ' 1.36% ',
  ' 168,528 ',
  ' 12 ',
  ' 1,083,300 ',
  ' −3,179 ',
  ' 2.5 ',
  ' 25.2 ',
  ' 70.6% ',
  ' 0.15% '],
 [' 80 ',
  '  Tunisia  ',
  ' 12,348,573 ',
  ' 0.58% ',
  ' 71,464 ',
  ' 79 ',
  ' 155,360 ',
  ' −14,523 ',
  ' 1.8 ',
  ' 32.9 ',
  ' 71.7% ',
  ' 0.15% '],
 [' 81 ',
  '  South Sudan  ',
  ' 12,188,788 ',
  ' 2.05% ',
  ' 245,380 ',
  ' 20 ',
  ' 610,952 ',
  ' 6,145 ',
  ' 3.71 ',
  ' 18.7 ',
  ' 27.7% ',
  ' 0.15% '],
 [' 82 ',
  '  Haiti  ',
  ' 11,906,095 ',
  ' 1.13% ',
  ' 133,538 ',
  ' 432 ',
  ' 27,560 ',
  ' −32,052 ',
  ' 2.59 ',
  ' 24.1 ',
  ' 61.7% ',
  ' 0.14% '],
 [' 83 ',
  '  Belgium  ',
  ' 11,758,603 ',
  ' 0.17% ',
  ' 19,840 ',
  ' 388 ',
  ' 30,280 ',
  ' 31,989 ',
  ' 1.39 ',
  ' 41.9 ',
  ' 98.8% ',
  ' 0.14% '],
 [' 84 ',
  '  Jordan  ',
  ' 11,520,684 ',
  ' −0.28% ',
  ' −32,192 ',
  ' 130 ',
  ' 88,780 ',
  ' −303,267 ',
  ' 2.57 ',
  ' 24.7 ',
  ' 85.1% ',
  ' 0.14% '],
 [' 85 ',
  '  Dominican Republic  ',
  ' 11,520,487 ',
  ' 0.81% ',
  ' 92,930 ',
  ' 238 ',
  ' 48,320 ',
  ' −35,306 ',
  ' 2.19 ',
  ' 28.3 ',
  ' 86.4% ',
  ' 0.14% '],
 [' 86 ',
  '  United Arab Emirates  ',
  ' 11,346,000 ',
  ' 2.89% ',
  ' 318,871 ',
  ' 136 ',
  ' 83,600 ',
  ' 158,634 ',
  ' 1.21 ',
  ' 31.6 ',
  ' 81.1% ',
  ' 0.14% '],
 [' 87 ',
  '  Honduras  ',
  ' 11,005,850 ',
  ' 1.66% ',
  ' 180,147 ',
  ' 98 ',
  ' 111,890 ',
  ' −4,778 ',
  ' 2.45 ',
  ' 24.2 ',
  ' 58.3% ',
  ' 0.13% '],
 [' 88 ',
  '  Cuba  ',
  ' 10,937,203 ',
  ' −0.39% ',
  ' −42,580 ',
  ' 103 ',
  ' 106,440 ',
  ' −22,244 ',
  ' 1.45 ',
  ' 42.2 ',
  ' 81.9% ',
  ' 0.13% '],
 [' 89 ',
  '  Tajikistan  ',
  ' 10,786,734 ',
  ' 1.85% ',
  ' 195,807 ',
  ' 77 ',
  ' 139,960 ',
  ' −21,606 ',
  ' 2.99 ',
  ' 22.2 ',
  ' 27.7% ',
  ' 0.13% '],
 [' 90 ',
  '  Papua New Guinea  ',
  ' 10,762,817 ',
  ' 1.76% ',
  ' 186,315 ',
  ' 24 ',
  ' 452,860 ',
  ' −284 ',
  ' 3.03 ',
  ' 22.8 ',
  ' 12.6% ',
  ' 0.13% '],
 [' 91 ',
  '  Sweden  ',
  ' 10,656,633 ',
  ' 0.47% ',
  ' 49,634 ',
  ' 26 ',
  ' 410,340 ',
  ' 47,079 ',
  ' 1.44 ',
  ' 40.3 ',
  ' 87.4% ',
  ' 0.13% '],
 [' 92 ',
  '  Czech Republic (Czechia)  ',
  ' 10,609,239 ',
  ' −1.18% ',
  ' −126,620 ',
  ' 137 ',
  ' 77,240 ',
  ' −112,188 ',
  ' 1.47 ',
  ' 43.8 ',
  ' 75% ',
  ' 0.13% '],
 [' 93 ',
  '  Portugal  ',
  ' 10,411,834 ',
  ' −0.13% ',
  ' −13,458 ',
  ' 114 ',
  ' 91,590 ',
  ' 16,472 ',
  ' 1.52 ',
  ' 46.9 ',
  ' 66.5% ',
  ' 0.13% '],
 [' 94 ',
  '  Azerbaijan  ',
  ' 10,397,713 ',
  ' 0.59% ',
  ' 61,136 ',
  ' 126 ',
  ' 82,658 ',
  ' 8,731 ',
  ' 1.67 ',
  ' 33.6 ',
  ' 58.7% ',
  ' 0.13% '],
 [' 95 ',
  '  Greece  ',
  ' 9,938,844 ',
  ' −1.08% ',
  ' −108,973 ',
  ' 77 ',
  ' 128,900 ',
  ' 16,636 ',
  ' 1.34 ',
  ' 46.8 ',
  ' 89.5% ',
  ' 0.12% '],
 [' 96 ',
  '  Togo  ',
  ' 9,721,608 ',
  ' 2.17% ',
  ' 206,372 ',
  ' 179 ',
  ' 54,390 ',
  ' −15,010 ',
  ' 4.07 ',
  ' 19.1 ',
  ' 44.2% ',
  ' 0.12% '],
 [' 97 ',
  '  Hungary  ',
  ' 9,632,287 ',
  ' −0.45% ',
  ' −43,848 ',
  ' 106 ',
  ' 90,530 ',
  ' −16,331 ',
  ' 1.5 ',
  ' 43.9 ',
  ' 72% ',
  ' 0.12% '],
 [' 98 ',
  '  Israel  ',
  ' 9,517,181 ',
  ' 1.39% ',
  ' 130,160 ',
  ' 440 ',
  ' 21,640 ',
  ' 11,466 ',
  ' 2.75 ',
  ' 29.2 ',
  ' 91.4% ',
  ' 0.12% '],
 [' 99 ',
  '  Austria  ',
  ' 9,113,574 ',
  ' −0.08% ',
  ' −7,239 ',
  ' 111 ',
  ' 82,409 ',
  ' 11,254 ',
  ' 1.33 ',
  ' 43.6 ',
  ' 58.6% ',
  ' 0.11% '],
 [' 100 ',
  '  Belarus  ',
  ' 8,997,603 ',
  ' −0.65% ',
  ' −59,093 ',
  ' 44 ',
  ' 202,910 ',
  ' −3,020 ',
  ' 1.23 ',
  ' 41.3 ',
  ' 84.4% ',
  ' 0.11% '],
 [' 101 ',
  '  Switzerland  ',
  ' 8,967,407 ',
  ' 0.51% ',
  ' 45,426 ',
  ' 227 ',
  ' 39,516 ',
  ' 37,253 ',
  ' 1.44 ',
  ' 42.9 ',
  ' 74.4% ',
  ' 0.11% '],
 [' 102 ',
  '  Sierra Leone  ',
  ' 8,819,794 ',
  ' 2.06% ',
  ' 177,772 ',
  ' 122 ',
  ' 72,180 ',
  ' −11,309 ',
  ' 3.61 ',
  ' 19.7 ',
  ' 45.5% ',
  ' 0.11% '],
 [' 103 ',
  '  Laos  ',
  ' 7,873,046 ',
  ' 1.33% ',
  ' 103,227 ',
  ' 34 ',
  ' 230,800 ',
  ' −10,645 ',
  ' 2.36 ',
  ' 24.9 ',
  ' 38.3% ',
  ' 0.096% '],
 [' 104 ',
  '  Turkmenistan  ',
  ' 7,618,847 ',
  ' 1.66% ',
  ' 124,349 ',
  ' 16 ',
  ' 469,930 ',
  ' 13,268 ',
  ' 2.63 ',
  ' 26.9 ',
  ' 46.5% ',
  ' 0.093% '],
 [' 105 ',
  '  Libya  ',
  ' 7,458,555 ',
  ' 1.05% ',
  ' 77,532 ',
  ' 4 ',
  ' 1,759,540 ',
  ' −172 ',
  ' 2.25 ',
  ' 27.7 ',
  ' 77.5% ',
  ' 0.091% '],
 [' 106 ',
  '  Hong Kong  ',
  ' 7,396,076 ',
  ' −0.25% ',
  ' −18,833 ',
  ' 7,044 ',
  ' 1,050 ',
  ' 17,863 ',
  ' 0.73 ',
  ' 47.4 ',
  ' ',
  ' 0.090% '],
 [' 107 ',
  '  Kyrgyzstan  ',
  ' 7,295,034 ',
  ' 1.52% ',
  ' 109,025 ',
  ' 38 ',
  ' 191,800 ',
  ' 1,815 ',
  ' 2.75 ',
  ' 25.4 ',
  ' 35.3% ',
  ' 0.089% '],
 [' 108 ',
  '  Paraguay  ',
  ' 7,013,078 ',
  ' 1.21% ',
  ' 83,925 ',
  ' 18 ',
  ' 397,300 ',
  ' −12,423 ',
  ' 2.4 ',
  ' 27 ',
  ' 68% ',
  ' 0.085% '],
 [' 109 ',
  '  Nicaragua  ',
  ' 7,007,502 ',
  ' 1.32% ',
  ' 91,362 ',
  ' 58 ',
  ' 120,340 ',
  ' −8,371 ',
  ' 2.18 ',
  ' 26 ',
  ' 58.1% ',
  ' 0.085% '],
 [' 110 ',
  '  Bulgaria  ',
  ' 6,714,560 ',
  ' −0.64% ',
  ' −43,129 ',
  ' 62 ',
  ' 108,560 ',
  ' −2,961 ',
  ' 1.74 ',
  ' 44.8 ',
  ' 77.1% ',
  ' 0.082% '],
 [' 111 ',
  '  Serbia  ',
  ' 6,689,039 ',
  ' −0.7% ',
  ' −47,177 ',
  ' 76 ',
  ' 87,460 ',
  ' −13,086 ',
  ' 1.5 ',
  ' 44.4 ',
  ' 73.6% ',
  ' 0.081% '],
 [' 112 ',
  '  Congo  ',
  ' 6,484,437 ',
  ' 2.39% ',
  ' 151,476 ',
  ' 19 ',
  ' 341,500 ',
  ' −2,999 ',
  ' 4.05 ',
  ' 18.6 ',
  ' 69.8% ',
  ' 0.079% '],
 [' 113 ',
  '  El Salvador  ',
  ' 6,365,503 ',
  ' 0.43% ',
  ' 27,310 ',
  ' 307 ',
  ' 20,720 ',
  ' −23,934 ',
  ' 1.75 ',
  ' 27.9 ',
  ' 79.9% ',
  ' 0.077% '],
 [' 114 ',
  '  Denmark  ',
  ' 6,002,507 ',
  ' 0.42% ',
  ' 25,095 ',
  ' 141 ',
  ' 42,430 ',
  ' 22,103 ',
  ' 1.52 ',
  ' 41.3 ',
  ' 87.4% ',
  ' 0.073% '],
 [' 115 ',
  '  Singapore  ',
  ' 5,870,750 ',
  ' 0.66% ',
  ' 38,363 ',
  ' 8,387 ',
  ' 700 ',
  ' 16,892 ',
  ' 0.96 ',
  ' 36.2 ',
  ' ',
  ' 0.071% '],
 [' 116 ',
  '  Lebanon  ',
  ' 5,849,421 ',
  ' 0.75% ',
  ' 43,459 ',
  ' 572 ',
  ' 10,230 ',
  ' −10,230 ',
  ' 2.21 ',
  ' 28.8 ',
  ' 86% ',
  ' 0.071% '],
 [' 117 ',
  '  Liberia  ',
  ' 5,731,206 ',
  ' 2.11% ',
  ' 118,389 ',
  ' 60 ',
  ' 96,320 ',
  ' −9,870 ',
  ' 3.79 ',
  ' 18.8 ',
  ' 55% ',
  ' 0.070% '],
 [' 118 ',
  '  Finland  ',
  ' 5,623,329 ',
  ' 0.11% ',
  ' 6,019 ',
  ' 19 ',
  ' 303,890 ',
  ' 18,246 ',
  ' 1.3 ',
  ' 43.2 ',
  ' 86.7% ',
  ' 0.068% '],
 [' 119 ',
  '  Norway  ',
  ' 5,623,071 ',
  ' 0.83% ',
  ' 46,411 ',
  ' 15 ',
  ' 365,268 ',
  ' 29,798 ',
  ' 1.42 ',
  ' 39.8 ',
  ' 85.9% ',
  ' 0.068% '],
 [' 120 ',
  '  State of Palestine  ',
  ' 5,589,623 ',
  ' 1.71% ',
  ' 94,180 ',
  ' 929 ',
  ' 6,020 ',
  ' −23,156 ',
  ' 3.19 ',
  ' 20.1 ',
  ' 84.2% ',
  ' 0.068% '],
 [' 121 ',
  '  Central African Republic  ',
  ' 5,513,282 ',
  ' 3.43% ',
  ' 182,592 ',
  ' 9 ',
  ' 622,980 ',
  ' −14,693 ',
  ' 5.81 ',
  ' 14.5 ',
  ' 44.5% ',

In [148]:
population_count.pop(0)

[]

In [149]:
population_count

[[' 1 ',
  '  India  ',
  ' 1,463,865,525 ',
  ' 0.89% ',
  ' 12,929,734 ',
  ' 492 ',
  ' 2,973,190 ',
  ' −495,753 ',
  ' 1.94 ',
  ' 28.8 ',
  ' 37.1% ',
  ' 17.78% '],
 [' 2 ',
  '  China  ',
  ' 1,416,096,094 ',
  ' −0.23% ',
  ' −3,225,184 ',
  ' 151 ',
  ' 9,388,211 ',
  ' −268,126 ',
  ' 1.02 ',
  ' 40.1 ',
  ' 67.5% ',
  ' 17.20% '],
 [' 3 ',
  '  United States  ',
  ' 347,275,807 ',
  ' 0.54% ',
  ' 1,849,236 ',
  ' 38 ',
  ' 9,147,420 ',
  ' 1,230,663 ',
  ' 1.62 ',
  ' 38.5 ',
  ' 82.8% ',
  ' 4.22% '],
 [' 4 ',
  '  Indonesia  ',
  ' 285,721,236 ',
  ' 0.79% ',
  ' 2,233,305 ',
  ' 158 ',
  ' 1,811,570 ',
  ' −39,509 ',
  ' 2.1 ',
  ' 30.4 ',
  ' 59.6% ',
  ' 3.47% '],
 [' 5 ',
  '  Pakistan  ',
  ' 255,219,554 ',
  ' 1.57% ',
  ' 3,950,390 ',
  ' 331 ',
  ' 770,880 ',
  ' −1,235,336 ',
  ' 3.5 ',
  ' 20.6 ',
  ' 34.4% ',
  ' 3.10% '],
 [' 6 ',
  '  Nigeria  ',
  ' 237,527,782 ',
  ' 2.08% ',
  ' 4,848,304 ',
  ' 261 ',
  ' 910,770 ',
  ' −15,258 ',
  ' 4.3 ',
  ' 18.1 ',
  ' 54.9% ',
  ' 2.89% '],
 [' 7 ',
  '  Brazil  ',
  ' 212,812,405 ',
  ' 0.38% ',
  ' 813,832 ',
  ' 25 ',
  ' 8,358,140 ',
  ' −217,283 ',
  ' 1.6 ',
  ' 34.8 ',
  ' 91.4% ',
  ' 2.59% '],
 [' 8 ',
  '  Bangladesh  ',
  ' 175,686,899 ',
  ' 1.22% ',
  ' 2,124,535 ',
  ' 1,350 ',
  ' 130,170 ',
  ' −402,100 ',
  ' 2.11 ',
  ' 26 ',
  ' 42.6% ',
  ' 2.13% '],
 [' 9 ',
  '  Russia  ',
  ' 143,997,393 ',
  ' −0.57% ',
  ' −823,030 ',
  ' 9 ',
  ' 16,376,870 ',
  ' −251,822 ',
  ' 1.47 ',
  ' 40.3 ',
  ' 75% ',
  ' 1.75% '],
 [' 10 ',
  '  Ethiopia  ',
  ' 135,472,051 ',
  ' 2.58% ',
  ' 3,412,284 ',
  ' 135 ',
  ' 1,000,000 ',
  ' 24,054 ',
  ' 3.81 ',
  ' 19.1 ',
  ' 22.5% ',
  ' 1.65% '],
 [' 11 ',
  '  Mexico  ',
  ' 131,946,900 ',
  ' 0.83% ',
  ' 1,085,893 ',
  ' 68 ',
  ' 1,943,950 ',
  ' −108,037 ',
  ' 1.87 ',
  ' 29.6 ',
  ' 87.9% ',
  ' 1.60% '],
 [' 12 ',
  '  Japan  ',
  ' 123,103,479 ',
  ' −0.52% ',
  ' −649,562 ',
  ' 338 ',
  ' 364,555 ',
  ' 140,579 ',
  ' 1.23 ',
  ' 49.8 ',
  ' 93.1% ',
  ' 1.50% '],
 [' 13 ',
  '  Egypt  ',
  ' 118,365,995 ',
  ' 1.57% ',
  ' 1,827,737 ',
  ' 119 ',
  ' 995,450 ',
  ' −57,305 ',
  ' 2.71 ',
  ' 24.5 ',
  ' 40.9% ',
  ' 1.44% '],
 [' 14 ',
  '  Philippines  ',
  ' 116,786,962 ',
  ' 0.81% ',
  ' 943,292 ',
  ' 392 ',
  ' 298,170 ',
  ' −149,315 ',
  ' 1.88 ',
  ' 26.1 ',
  ' 49.3% ',
  ' 1.42% '],
 [' 15 ',
  '  DR Congo  ',
  ' 112,832,473 ',
  ' 3.25% ',
  ' 3,556,208 ',
  ' 50 ',
  ' 2,267,050 ',
  ' −27,309 ',
  ' 5.9 ',
  ' 15.8 ',
  ' 45% ',
  ' 1.37% '],
 [' 16 ',
  '  Vietnam  ',
  ' 101,598,527 ',
  ' 0.6% ',
  ' 610,841 ',
  ' 328 ',
  ' 310,070 ',
  ' −48,171 ',
  ' 1.88 ',
  ' 33.4 ',
  ' 41.4% ',
  ' 1.23% '],
 [' 17 ',
  '  Iran  ',
  ' 92,417,681 ',
  ' 0.93% ',
  ' 849,943 ',
  ' 57 ',
  ' 1,628,550 ',
  ' 116,786 ',
  ' 1.67 ',
  ' 34 ',
  ' 73.3% ',
  ' 1.12% '],
 [' 18 ',
  '  Turkey  ',
  ' 87,685,426 ',
  ' 0.24% ',
  ' 211,621 ',
  ' 114 ',
  ' 769,630 ',
  ' −258,205 ',
  ' 1.62 ',
  ' 33.5 ',
  ' 76.9% ',
  ' 1.07% '],
 [' 19 ',
  '  Germany  ',
  ' 84,075,075 ',
  ' −0.56% ',
  ' −477,167 ',
  ' 241 ',
  ' 348,560 ',
  ' −334,072 ',
  ' 1.46 ',
  ' 45.5 ',
  ' 76.5% ',
  ' 1.02% '],
 [' 20 ',
  '  Thailand  ',
  ' 71,619,863 ',
  ' −0.07% ',
  ' −48,148 ',
  ' 140 ',
  ' 510,890 ',
  ' 27,509 ',
  ' 1.2 ',
  ' 40.6 ',
  ' 53.5% ',
  ' 0.87% '],
 [' 21 ',
  '  Tanzania  ',
  ' 70,545,865 ',
  ' 2.9% ',
  ' 1,985,708 ',
  ' 80 ',
  ' 885,800 ',
  ' −12,730 ',
  ' 4.47 ',
  ' 17.5 ',
  ' 40% ',
  ' 0.86% '],
 [' 22 ',
  '  United Kingdom  ',
  ' 69,551,332 ',
  ' 0.6% ',
  ' 413,140 ',
  ' 287 ',
  ' 241,930 ',
  ' 389,911 ',
  ' 1.54 ',
  ' 40.1 ',
  ' 84.5% ',
  ' 0.84% '],
 [' 23 ',
  '  France  ',
  ' 66,650,804 ',
  ' 0.15% ',
  ' 102,274 ',
  ' 122 ',
  ' 547,557 ',
  ' 91,737 ',
  ' 1.64 ',
  ' 42.3 ',
  ' 82.5% ',
  ' 0.81% '],
 [' 24 ',
  '  South Africa  ',
  ' 64,747,319 ',
  ' 1.16% ',
  ' 740,132 ',
  ' 53 ',
  ' 1,213,090 ',
  ' 146,370 ',
  ' 2.19 ',
  ' 28.7 ',
  ' 66.6% ',
  ' 0.79% '],
 [' 25 ',
  '  Italy  ',
  ' 59,146,260 ',
  ' −0.33% ',
  ' −196,607 ',
  ' 201 ',
  ' 294,140 ',
  ' 75,448 ',
  ' 1.21 ',
  ' 48.2 ',
  ' 72% ',
  ' 0.72% '],
 [' 26 ',
  '  Kenya  ',
  ' 57,532,493 ',
  ' 1.95% ',
  ' 1,099,549 ',
  ' 101 ',
  ' 569,140 ',
  ' −27,330 ',
  ' 3.12 ',
  ' 20 ',
  ' 31.9% ',
  ' 0.70% '],
 [' 27 ',
  '  Myanmar  ',
  ' 54,850,648 ',
  ' 0.64% ',
  ' 350,557 ',
  ' 84 ',
  ' 653,290 ',
  ' −39,661 ',
  ' 2.08 ',
  ' 30.1 ',
  ' 34.1% ',
  ' 0.67% '],
 [' 28 ',
  '  Colombia  ',
  ' 53,425,635 ',
  ' 1.02% ',
  ' 539,272 ',
  ' 48 ',
  ' 1,109,500 ',
  ' 129,139 ',
  ' 1.62 ',
  ' 32.5 ',
  ' 80.5% ',
  ' 0.65% '],
 [' 29 ',
  '  South Korea  ',
  ' 51,667,029 ',
  ' −0.1% ',
  ' −50,561 ',
  ' 531 ',
  ' 97,230 ',
  ' 65,731 ',
  ' 0.75 ',
  ' 45.6 ',
  ' 82.4% ',
  ' 0.63% '],
 [' 30 ',
  '  Sudan  ',
  ' 51,662,147 ',
  ' 2.4% ',
  ' 1,213,184 ',
  ' 29 ',
  ' 1,765,048 ',
  ' 291,469 ',
  ' 4.19 ',
  ' 18.5 ',
  ' 35.3% ',
  ' 0.63% '],
 [' 31 ',
  '  Uganda  ',
  ' 51,384,894 ',
  ' 2.74% ',
  ' 1,369,802 ',
  ' 257 ',
  ' 199,810 ',
  ' −119,059 ',
  ' 4.06 ',
  ' 16.9 ',
  ' 30% ',
  ' 0.62% '],
 [' 32 ',
  '  Spain  ',
  ' 47,889,958 ',
  ' −0.04% ',
  ' −20,568 ',
  ' 96 ',
  ' 498,800 ',
  ' 96,630 ',
  ' 1.23 ',
  ' 45.9 ',
  ' 79.3% ',
  ' 0.58% '],
 [' 33 ',
  '  Algeria  ',
  ' 47,435,312 ',
  ' 1.33% ',
  ' 621,004 ',
  ' 20 ',
  ' 2,381,740 ',
  ' −27,531 ',
  ' 2.67 ',
  ' 28.6 ',
  ' 74.4% ',
  ' 0.58% '],
 [' 34 ',
  '  Iraq  ',
  ' 47,020,774 ',
  ' 2.13% ',
  ' 978,759 ',
  ' 108 ',
  ' 434,320 ',
  ' −1,064 ',
  ' 3.17 ',
  ' 20.8 ',
  ' 72.4% ',
  ' 0.57% '],
 [' 35 ',
  '  Argentina  ',
  ' 45,851,378 ',
  ' 0.34% ',
  ' 155,219 ',
  ' 17 ',
  ' 2,736,690 ',
  ' 2,859 ',
  ' 1.5 ',
  ' 32.9 ',
  ' 96% ',
  ' 0.56% '],
 [' 36 ',
  '  Afghanistan  ',
  ' 43,844,111 ',
  ' 2.81% ',
  ' 1,196,619 ',
  ' 67 ',
  ' 652,860 ',
  ' −74,404 ',
  ' 4.66 ',
  ' 17.3 ',
  ' 26.7% ',
  ' 0.53% '],
 [' 37 ',
  '  Yemen  ',
  ' 41,773,878 ',
  ' 2.93% ',
  ' 1,190,714 ',
  ' 79 ',
  ' 527,970 ',
  ' −16,291 ',
  ' 4.41 ',
  ' 18.4 ',
  ' 33% ',
  ' 0.51% '],
 [' 38 ',
  '  Canada  ',
  ' 40,126,723 ',
  ' 0.97% ',
  ' 384,293 ',
  ' 4 ',
  ' 9,093,510 ',
  ' 326,204 ',
  ' 1.33 ',
  ' 40.6 ',
  ' 80.2% ',
  ' 0.49% '],
 [' 39 ',
  '  Angola  ',
  ' 39,040,039 ',
  ' 3.05% ',
  ' 1,154,190 ',
  ' 31 ',
  ' 1,246,700 ',
  ' −3,524 ',
  ' 4.95 ',
  ' 16.6 ',
  ' 68.8% ',
  ' 0.47% '],
 [' 40 ',
  '  Ukraine  ',
  ' 38,980,376 ',
  ' 2.96% ',
  ' 1,120,155 ',
  ' 67 ',
  ' 579,320 ',
  ' 1,702,358 ',
  ' 1 ',
  ' 41.8 ',
  ' 76.8% ',
  ' 0.47% '],
 [' 41 ',
  '  Morocco  ',
  ' 38,430,770 ',
  ' 0.92% ',
  ' 349,597 ',
  ' 86 ',
  ' 446,300 ',
  ' −56,254 ',
  ' 2.18 ',
  ' 29.8 ',
  ' 67.3% ',
  ' 0.47% '],
 [' 42 ',
  '  Poland  ',
  ' 38,140,910 ',
  ' −1.03% ',
  ' −398,291 ',
  ' 125 ',
  ' 306,230 ',
  ' −330,820 ',
  ' 1.31 ',
  ' 42.5 ',
  ' 59.2% ',
  ' 0.46% '],
 [' 43 ',
  '  Uzbekistan  ',
  ' 37,053,428 ',
  ' 1.9% ',
  ' 691,569 ',
  ' 87 ',
  ' 425,400 ',
  ' −6,987 ',
  ' 3.45 ',
  ' 27 ',
  ' 48.1% ',
  ' 0.45% '],
 [' 44 ',
  '  Malaysia  ',
  ' 35,977,838 ',
  ' 1.18% ',
  ' 420,165 ',
  ' 110 ',
  ' 328,550 ',
  ' 166,615 ',
  ' 1.53 ',
  ' 31 ',
  ' 77.4% ',
  ' 0.44% '],
 [' 45 ',
  '  Mozambique  ',
  ' 35,631,653 ',
  ' 2.89% ',
  ' 999,887 ',
  ' 45 ',
  ' 786,380 ',
  ' −65,573 ',
  ' 4.62 ',
  ' 16.5 ',
  ' 41.6% ',
  ' 0.43% '],
 [' 46 ',
  '  Ghana  ',
  ' 35,064,272 ',
  ' 1.85% ',
  ' 636,858 ',
  ' 154 ',
  ' 227,540 ',
  ' −17,079 ',
  ' 3.3 ',
  ' 21.3 ',
  ' 58.6% ',
  ' 0.43% '],
 [' 47 ',
  '  Peru  ',
  ' 34,576,665 ',
  ' 1.05% ',
  ' 358,817 ',
  ' 27 ',
  ' 1,280,000 ',
  ' 11,931 ',
  ' 1.94 ',
  ' 30.2 ',
  ' 80.6% ',
  ' 0.42% '],
 [' 48 ',
  '  Saudi Arabia  ',
  ' 34,566,328 ',
  ' 1.78% ',
  ' 603,571 ',
  ' 16 ',
  ' 2,149,690 ',
  ' 119,738 ',
  ' 2.29 ',
  ' 29.6 ',
  ' 92.1% ',
  ' 0.42% '],
 [' 49 ',
  '  Madagascar  ',
  ' 32,740,678 ',
  ' 2.43% ',
  ' 775,722 ',
  ' 56 ',
  ' 581,795 ',
  ' −2,227 ',
  ' 3.85 ',
  ' 19.2 ',
  ' 40.3% ',
  ' 0.40% '],
 [' 50 ',
  "  Côte d'Ivoire  ",
  ' 32,711,547 ',
  ' 2.43% ',
  ' 777,317 ',
  ' 103 ',
  ' 318,000 ',
  ' 11,305 ',
  ' 4.17 ',
  ' 18.3 ',
  ' 49% ',
  ' 0.40% '],
 [' 51 ',
  '  Cameroon  ',
  ' 29,879,337 ',
  ' 2.59% ',
  ' 755,593 ',
  ' 63 ',
  ' 472,710 ',
  ' −15,379 ',
  ' 4.18 ',
  ' 18 ',
  ' 59.4% ',
  ' 0.36% '],
 [' 52 ',
  '  Nepal  ',
  ' 29,618,118 ',
  ' −0.11% ',
  ' −32,936 ',
  ' 207 ',
  ' 143,350 ',
  ' −364,699 ',
  ' 1.94 ',
  ' 25.3 ',
  ' 24.5% ',
  ' 0.36% '],
 [' 53 ',
  '  Venezuela  ',
  ' 28,516,896 ',
  ' 0.39% ',
  ' 111,353 ',
  ' 32 ',
  ' 882,050 ',
  ' −100,467 ',
  ' 2.06 ',
  ' 29.4 ',
  ' ',
  ' 0.35% '],
 [' 54 ',
  '  Niger  ',
  ' 27,917,831 ',
  ' 3.28% ',
  ' 885,419 ',
  ' 22 ',
  ' 1,266,700 ',
  ' −7,704 ',
  ' 5.79 ',
  ' 15.6 ',
  ' 18.2% ',
  ' 0.34% '],
 [' 55 ',
  '  Australia  ',
  ' 26,974,026 ',
  ' 0.98% ',
  ' 260,821 ',
  ' 4 ',
  ' 7,682,300 ',
  ' 137,109 ',
  ' 1.64 ',
  ' 38.3 ',
  ' 86.5% ',
  ' 0.33% '],
 [' 56 ',
  '  North Korea  ',
  ' 26,571,036 ',
  ' 0.27% ',
  ' 72,213 ',
  ' 221 ',
  ' 120,410 ',
  ' −2,787 ',
  ' 1.77 ',
  ' 36.5 ',
  ' 63.3% ',
  ' 0.32% '],
 [' 57 ',
  '  Syria  ',
  ' 25,620,427 ',
  ' 3.84% ',
  ' 947,667 ',
  ' 140 ',
  ' 183,630 ',
  ' 421,693 ',
  ' 2.66 ',
  ' 23.3 ',
  ' 53.6% ',
  ' 0.31% '],
 [' 58 ',
  '  Mali  ',
  ' 25,198,821 ',
  ' 2.94% ',
  ' 720,226 ',
  ' 21 ',
  ' 1,220,190 ',
  ' −48,019 ',
  ' 5.42 ',
  ' 15.7 ',
  ' 44.4% ',
  ' 0.31% '],
 [' 59 ',
  '  Burkina Faso  ',
  ' 24,074,580 ',
  ' 2.23% ',
  ' 525,799 ',
  ' 88 ',
  ' 273,600 ',
  ' −27,130 ',
  ' 4 ',
  ' 17.7 ',
  ' 33.7% ',
  ' 0.29% '],
 [' 60 ',
  '  Sri Lanka  ',
  ' 23,229,470 ',
  ' 0.54% ',
  ' 125,905 ',
  ' 370 ',
  ' 62,710 ',
  ' −30,724 ',
  ' 1.94 ',
  ' 33.3 ',
  ' 18.1% ',
  ' 0.28% '],
 [' 61 ',
  '  Taiwan  ',
  ' 23,112,793 ',
  ' −0.44% ',
  ' −101,169 ',
  ' 653 ',
  ' 35,410 ',
  ' −20,947 ',
  ' 0.86 ',
  ' 44.8 ',
  ' 84% ',
  ' 0.28% '],
 [' 62 ',
  '  Malawi  ',
  ' 22,216,120 ',
  ' 2.59% ',
  ' 560,834 ',
  ' 236 ',
  ' 94,280 ',
  ' −5,628 ',
  ' 3.53 ',
  ' 18.1 ',
  ' 19.8% ',
  ' 0.27% '],
 [' 63 ',
  '  Zambia  ',
  ' 21,913,874 ',
  ' 2.81% ',
  ' 598,918 ',
  ' 29 ',
  ' 743,390 ',
  ' 6,562 ',
  ' 3.97 ',
  ' 17.9 ',
  ' 46.8% ',
  ' 0.27% '],
 [' 64 ',
  '  Chad  ',
  ' 21,003,705 ',
  ' 3.47% ',
  ' 704,582 ',
  ' 17 ',
  ' 1,259,200 ',
  ' −123,104 ',
  ' 5.94 ',
  ' 15.8 ',
  ' 22.4% ',
  ' 0.26% '],
 [' 65 ',
  '  Kazakhstan  ',
  ' 20,843,754 ',
  ' 1.22% ',
  ' 251,183 ',
  ' 8 ',
  ' 2,699,700 ',
  ' −8,834 ',
  ' 2.95 ',
  ' 29.7 ',
  ' 55.1% ',
  ' 0.25% '],
 [' 66 ',
  '  Chile  ',
  ' 19,859,921 ',
  ' 0.48% ',
  ' 95,150 ',
  ' 27 ',
  ' 743,532 ',
  ' 51,712 ',
  ' 1.13 ',
  ' 36.9 ',
  ' 84.8% ',
  ' 0.24% '],
 [' 67 ',
  '  Somalia  ',
  ' 19,654,739 ',
  ' 3.4% ',
  ' 645,588 ',
  ' 31 ',
  ' 627,340 ',
  ' 12,077 ',
  ' 5.91 ',
  ' 15.6 ',
  ' 46.6% ',
  ' 0.24% '],
 [' 68 ',
  '  Senegal  ',
  ' 18,931,966 ',
  ' 2.32% ',
  ' 429,982 ',
  ' 98 ',
  ' 192,530 ',
  ' −12,636 ',
  ' 3.71 ',
  ' 19.6 ',
  ' 52.3% ',
  ' 0.23% '],
 [' 69 ',
  '  Romania  ',
  ' 18,908,650 ',
  ' −0.56% ',
  ' −106,438 ',
  ' 82 ',
  ' 230,170 ',
  ' −29,041 ',
  ' 1.71 ',
  ' 43.2 ',
  ' 55.2% ',
  ' 0.23% '],
 [' 70 ',
  '  Guatemala  ',
  ' 18,687,881 ',
  ' 1.53% ',
  ' 281,522 ',
  ' 174 ',
  ' 107,160 ',
  ' −7,959 ',
  ' 2.26 ',
  ' 23.4 ',
  ' 56.6% ',
  ' 0.23% '],
 [' 71 ',
  '  Netherlands  ',
  ' 18,346,819 ',
  ' 0.65% ',
  ' 118,077 ',
  ' 544 ',
  ' 33,720 ',
  ' 104,681 ',
  ' 1.44 ',
  ' 41.5 ',
  ' 88.9% ',
  ' 0.22% '],
 [' 72 ',
  '  Ecuador  ',
  ' 18,289,896 ',
  ' 0.85% ',
  ' 154,418 ',
  ' 74 ',
  ' 248,360 ',
  ' −17,219 ',
  ' 1.79 ',
  ' 29.3 ',
  ' 66% ',
  ' 0.22% '],
 [' 73 ',
  '  Cambodia  ',
  ' 17,847,982 ',
  ' 1.19% ',
  ' 209,181 ',
  ' 101 ',
  ' 176,520 ',
  ' −31,469 ',
  ' 2.51 ',
  ' 26.2 ',
  ' 26.5% ',
  ' 0.22% '],
 [' 74 ',
  '  Zimbabwe  ',
  ' 16,950,795 ',
  ' 1.9% ',
  ' 316,422 ',
  ' 44 ',
  ' 386,850 ',
  ' −54,555 ',
  ' 3.62 ',
  ' 18.1 ',
  ' 37.9% ',
  ' 0.21% '],
 [' 75 ',
  '  Guinea  ',
  ' 15,099,727 ',
  ' 2.34% ',
  ' 344,942 ',
  ' 61 ',
  ' 245,720 ',
  ' −16,282 ',
  ' 4.04 ',
  ' 18.3 ',
  ' 40.3% ',
  ' 0.18% '],
 [' 76 ',
  '  Benin  ',
  ' 14,814,460 ',
  ' 2.43% ',
  ' 351,736 ',
  ' 131 ',
  ' 112,760 ',
  ' −7,847 ',
  ' 4.42 ',
  ' 18 ',
  ' 47.8% ',
  ' 0.18% '],
 [' 77 ',
  '  Rwanda  ',
  ' 14,569,341 ',
  ' 2.19% ',
  ' 312,774 ',
  ' 591 ',
  ' 24,670 ',
  ' 6,282 ',
  ' 3.59 ',
  ' 19.9 ',
  ' 18.3% ',
  ' 0.18% '],
 [' 78 ',
  '  Burundi  ',
  ' 14,390,003 ',
  ' 2.44% ',
  ' 342,217 ',
  ' 560 ',
  ' 25,680 ',
  ' −34,727 ',
  ' 4.67 ',
  ' 16.4 ',
  ' 14.9% ',
  ' 0.17% '],
 [' 79 ',
  '  Bolivia  ',
  ' 12,581,843 ',
  ' 1.36% ',
  ' 168,528 ',
  ' 12 ',
  ' 1,083,300 ',
  ' −3,179 ',
  ' 2.5 ',
  ' 25.2 ',
  ' 70.6% ',
  ' 0.15% '],
 [' 80 ',
  '  Tunisia  ',
  ' 12,348,573 ',
  ' 0.58% ',
  ' 71,464 ',
  ' 79 ',
  ' 155,360 ',
  ' −14,523 ',
  ' 1.8 ',
  ' 32.9 ',
  ' 71.7% ',
  ' 0.15% '],
 [' 81 ',
  '  South Sudan  ',
  ' 12,188,788 ',
  ' 2.05% ',
  ' 245,380 ',
  ' 20 ',
  ' 610,952 ',
  ' 6,145 ',
  ' 3.71 ',
  ' 18.7 ',
  ' 27.7% ',
  ' 0.15% '],
 [' 82 ',
  '  Haiti  ',
  ' 11,906,095 ',
  ' 1.13% ',
  ' 133,538 ',
  ' 432 ',
  ' 27,560 ',
  ' −32,052 ',
  ' 2.59 ',
  ' 24.1 ',
  ' 61.7% ',
  ' 0.14% '],
 [' 83 ',
  '  Belgium  ',
  ' 11,758,603 ',
  ' 0.17% ',
  ' 19,840 ',
  ' 388 ',
  ' 30,280 ',
  ' 31,989 ',
  ' 1.39 ',
  ' 41.9 ',
  ' 98.8% ',
  ' 0.14% '],
 [' 84 ',
  '  Jordan  ',
  ' 11,520,684 ',
  ' −0.28% ',
  ' −32,192 ',
  ' 130 ',
  ' 88,780 ',
  ' −303,267 ',
  ' 2.57 ',
  ' 24.7 ',
  ' 85.1% ',
  ' 0.14% '],
 [' 85 ',
  '  Dominican Republic  ',
  ' 11,520,487 ',
  ' 0.81% ',
  ' 92,930 ',
  ' 238 ',
  ' 48,320 ',
  ' −35,306 ',
  ' 2.19 ',
  ' 28.3 ',
  ' 86.4% ',
  ' 0.14% '],
 [' 86 ',
  '  United Arab Emirates  ',
  ' 11,346,000 ',
  ' 2.89% ',
  ' 318,871 ',
  ' 136 ',
  ' 83,600 ',
  ' 158,634 ',
  ' 1.21 ',
  ' 31.6 ',
  ' 81.1% ',
  ' 0.14% '],
 [' 87 ',
  '  Honduras  ',
  ' 11,005,850 ',
  ' 1.66% ',
  ' 180,147 ',
  ' 98 ',
  ' 111,890 ',
  ' −4,778 ',
  ' 2.45 ',
  ' 24.2 ',
  ' 58.3% ',
  ' 0.13% '],
 [' 88 ',
  '  Cuba  ',
  ' 10,937,203 ',
  ' −0.39% ',
  ' −42,580 ',
  ' 103 ',
  ' 106,440 ',
  ' −22,244 ',
  ' 1.45 ',
  ' 42.2 ',
  ' 81.9% ',
  ' 0.13% '],
 [' 89 ',
  '  Tajikistan  ',
  ' 10,786,734 ',
  ' 1.85% ',
  ' 195,807 ',
  ' 77 ',
  ' 139,960 ',
  ' −21,606 ',
  ' 2.99 ',
  ' 22.2 ',
  ' 27.7% ',
  ' 0.13% '],
 [' 90 ',
  '  Papua New Guinea  ',
  ' 10,762,817 ',
  ' 1.76% ',
  ' 186,315 ',
  ' 24 ',
  ' 452,860 ',
  ' −284 ',
  ' 3.03 ',
  ' 22.8 ',
  ' 12.6% ',
  ' 0.13% '],
 [' 91 ',
  '  Sweden  ',
  ' 10,656,633 ',
  ' 0.47% ',
  ' 49,634 ',
  ' 26 ',
  ' 410,340 ',
  ' 47,079 ',
  ' 1.44 ',
  ' 40.3 ',
  ' 87.4% ',
  ' 0.13% '],
 [' 92 ',
  '  Czech Republic (Czechia)  ',
  ' 10,609,239 ',
  ' −1.18% ',
  ' −126,620 ',
  ' 137 ',
  ' 77,240 ',
  ' −112,188 ',
  ' 1.47 ',
  ' 43.8 ',
  ' 75% ',
  ' 0.13% '],
 [' 93 ',
  '  Portugal  ',
  ' 10,411,834 ',
  ' −0.13% ',
  ' −13,458 ',
  ' 114 ',
  ' 91,590 ',
  ' 16,472 ',
  ' 1.52 ',
  ' 46.9 ',
  ' 66.5% ',
  ' 0.13% '],
 [' 94 ',
  '  Azerbaijan  ',
  ' 10,397,713 ',
  ' 0.59% ',
  ' 61,136 ',
  ' 126 ',
  ' 82,658 ',
  ' 8,731 ',
  ' 1.67 ',
  ' 33.6 ',
  ' 58.7% ',
  ' 0.13% '],
 [' 95 ',
  '  Greece  ',
  ' 9,938,844 ',
  ' −1.08% ',
  ' −108,973 ',
  ' 77 ',
  ' 128,900 ',
  ' 16,636 ',
  ' 1.34 ',
  ' 46.8 ',
  ' 89.5% ',
  ' 0.12% '],
 [' 96 ',
  '  Togo  ',
  ' 9,721,608 ',
  ' 2.17% ',
  ' 206,372 ',
  ' 179 ',
  ' 54,390 ',
  ' −15,010 ',
  ' 4.07 ',
  ' 19.1 ',
  ' 44.2% ',
  ' 0.12% '],
 [' 97 ',
  '  Hungary  ',
  ' 9,632,287 ',
  ' −0.45% ',
  ' −43,848 ',
  ' 106 ',
  ' 90,530 ',
  ' −16,331 ',
  ' 1.5 ',
  ' 43.9 ',
  ' 72% ',
  ' 0.12% '],
 [' 98 ',
  '  Israel  ',
  ' 9,517,181 ',
  ' 1.39% ',
  ' 130,160 ',
  ' 440 ',
  ' 21,640 ',
  ' 11,466 ',
  ' 2.75 ',
  ' 29.2 ',
  ' 91.4% ',
  ' 0.12% '],
 [' 99 ',
  '  Austria  ',
  ' 9,113,574 ',
  ' −0.08% ',
  ' −7,239 ',
  ' 111 ',
  ' 82,409 ',
  ' 11,254 ',
  ' 1.33 ',
  ' 43.6 ',
  ' 58.6% ',
  ' 0.11% '],
 [' 100 ',
  '  Belarus  ',
  ' 8,997,603 ',
  ' −0.65% ',
  ' −59,093 ',
  ' 44 ',
  ' 202,910 ',
  ' −3,020 ',
  ' 1.23 ',
  ' 41.3 ',
  ' 84.4% ',
  ' 0.11% '],
 [' 101 ',
  '  Switzerland  ',
  ' 8,967,407 ',
  ' 0.51% ',
  ' 45,426 ',
  ' 227 ',
  ' 39,516 ',
  ' 37,253 ',
  ' 1.44 ',
  ' 42.9 ',
  ' 74.4% ',
  ' 0.11% '],
 [' 102 ',
  '  Sierra Leone  ',
  ' 8,819,794 ',
  ' 2.06% ',
  ' 177,772 ',
  ' 122 ',
  ' 72,180 ',
  ' −11,309 ',
  ' 3.61 ',
  ' 19.7 ',
  ' 45.5% ',
  ' 0.11% '],
 [' 103 ',
  '  Laos  ',
  ' 7,873,046 ',
  ' 1.33% ',
  ' 103,227 ',
  ' 34 ',
  ' 230,800 ',
  ' −10,645 ',
  ' 2.36 ',
  ' 24.9 ',
  ' 38.3% ',
  ' 0.096% '],
 [' 104 ',
  '  Turkmenistan  ',
  ' 7,618,847 ',
  ' 1.66% ',
  ' 124,349 ',
  ' 16 ',
  ' 469,930 ',
  ' 13,268 ',
  ' 2.63 ',
  ' 26.9 ',
  ' 46.5% ',
  ' 0.093% '],
 [' 105 ',
  '  Libya  ',
  ' 7,458,555 ',
  ' 1.05% ',
  ' 77,532 ',
  ' 4 ',
  ' 1,759,540 ',
  ' −172 ',
  ' 2.25 ',
  ' 27.7 ',
  ' 77.5% ',
  ' 0.091% '],
 [' 106 ',
  '  Hong Kong  ',
  ' 7,396,076 ',
  ' −0.25% ',
  ' −18,833 ',
  ' 7,044 ',
  ' 1,050 ',
  ' 17,863 ',
  ' 0.73 ',
  ' 47.4 ',
  ' ',
  ' 0.090% '],
 [' 107 ',
  '  Kyrgyzstan  ',
  ' 7,295,034 ',
  ' 1.52% ',
  ' 109,025 ',
  ' 38 ',
  ' 191,800 ',
  ' 1,815 ',
  ' 2.75 ',
  ' 25.4 ',
  ' 35.3% ',
  ' 0.089% '],
 [' 108 ',
  '  Paraguay  ',
  ' 7,013,078 ',
  ' 1.21% ',
  ' 83,925 ',
  ' 18 ',
  ' 397,300 ',
  ' −12,423 ',
  ' 2.4 ',
  ' 27 ',
  ' 68% ',
  ' 0.085% '],
 [' 109 ',
  '  Nicaragua  ',
  ' 7,007,502 ',
  ' 1.32% ',
  ' 91,362 ',
  ' 58 ',
  ' 120,340 ',
  ' −8,371 ',
  ' 2.18 ',
  ' 26 ',
  ' 58.1% ',
  ' 0.085% '],
 [' 110 ',
  '  Bulgaria  ',
  ' 6,714,560 ',
  ' −0.64% ',
  ' −43,129 ',
  ' 62 ',
  ' 108,560 ',
  ' −2,961 ',
  ' 1.74 ',
  ' 44.8 ',
  ' 77.1% ',
  ' 0.082% '],
 [' 111 ',
  '  Serbia  ',
  ' 6,689,039 ',
  ' −0.7% ',
  ' −47,177 ',
  ' 76 ',
  ' 87,460 ',
  ' −13,086 ',
  ' 1.5 ',
  ' 44.4 ',
  ' 73.6% ',
  ' 0.081% '],
 [' 112 ',
  '  Congo  ',
  ' 6,484,437 ',
  ' 2.39% ',
  ' 151,476 ',
  ' 19 ',
  ' 341,500 ',
  ' −2,999 ',
  ' 4.05 ',
  ' 18.6 ',
  ' 69.8% ',
  ' 0.079% '],
 [' 113 ',
  '  El Salvador  ',
  ' 6,365,503 ',
  ' 0.43% ',
  ' 27,310 ',
  ' 307 ',
  ' 20,720 ',
  ' −23,934 ',
  ' 1.75 ',
  ' 27.9 ',
  ' 79.9% ',
  ' 0.077% '],
 [' 114 ',
  '  Denmark  ',
  ' 6,002,507 ',
  ' 0.42% ',
  ' 25,095 ',
  ' 141 ',
  ' 42,430 ',
  ' 22,103 ',
  ' 1.52 ',
  ' 41.3 ',
  ' 87.4% ',
  ' 0.073% '],
 [' 115 ',
  '  Singapore  ',
  ' 5,870,750 ',
  ' 0.66% ',
  ' 38,363 ',
  ' 8,387 ',
  ' 700 ',
  ' 16,892 ',
  ' 0.96 ',
  ' 36.2 ',
  ' ',
  ' 0.071% '],
 [' 116 ',
  '  Lebanon  ',
  ' 5,849,421 ',
  ' 0.75% ',
  ' 43,459 ',
  ' 572 ',
  ' 10,230 ',
  ' −10,230 ',
  ' 2.21 ',
  ' 28.8 ',
  ' 86% ',
  ' 0.071% '],
 [' 117 ',
  '  Liberia  ',
  ' 5,731,206 ',
  ' 2.11% ',
  ' 118,389 ',
  ' 60 ',
  ' 96,320 ',
  ' −9,870 ',
  ' 3.79 ',
  ' 18.8 ',
  ' 55% ',
  ' 0.070% '],
 [' 118 ',
  '  Finland  ',
  ' 5,623,329 ',
  ' 0.11% ',
  ' 6,019 ',
  ' 19 ',
  ' 303,890 ',
  ' 18,246 ',
  ' 1.3 ',
  ' 43.2 ',
  ' 86.7% ',
  ' 0.068% '],
 [' 119 ',
  '  Norway  ',
  ' 5,623,071 ',
  ' 0.83% ',
  ' 46,411 ',
  ' 15 ',
  ' 365,268 ',
  ' 29,798 ',
  ' 1.42 ',
  ' 39.8 ',
  ' 85.9% ',
  ' 0.068% '],
 [' 120 ',
  '  State of Palestine  ',
  ' 5,589,623 ',
  ' 1.71% ',
  ' 94,180 ',
  ' 929 ',
  ' 6,020 ',
  ' −23,156 ',
  ' 3.19 ',
  ' 20.1 ',
  ' 84.2% ',
  ' 0.068% '],
 [' 121 ',
  '  Central African Republic  ',
  ' 5,513,282 ',
  ' 3.43% ',
  ' 182,592 ',
  ' 9 ',
  ' 622,980 ',
  ' −14,693 ',
  ' 5.81 ',
  ' 14.5 ',
  ' 44.5% ',
  ' 0.067% '],

In [150]:
Sr_no=[]
Country=[]
Population2025=[]
Yearly_change=[]
Net_change=[]
Density=[]
Land_area=[]
Migrants=[]
Fert_rate=[]
Median_age=[]
Urban_pop_percent=[]
World_share=[]
for i in population_count:
    Sr_no.append(i[0])
    Country.append(i[1])
    Population2025.append(i[2])
    Yearly_change.append(i[3])
    Net_change.append(i[4])
    Density.append(i[5])
    Land_area.append(i[6])
    Migrants.append(i[7])
    Fert_rate.append(i[8])
    Median_age.append(i[9])
    Urban_pop_percent.append(i[10])
    World_share.append(i[11])
Data={'Sr_no':Sr_no,'Country':Country,'Population2025':Population2025,'Yearly_change':Yearly_change,'Net_change':Net_change,'Density':Density,'Land_area':Land_area,'Migrants':Migrants,'Fert_rate':Fert_rate,'Median_age':Median_age,'Urban_pop':Urban_pop_percent,'World_share':World_share}

In [151]:
Data

{'Sr_no': [' 1 ',
  ' 2 ',
  ' 3 ',
  ' 4 ',
  ' 5 ',
  ' 6 ',
  ' 7 ',
  ' 8 ',
  ' 9 ',
  ' 10 ',
  ' 11 ',
  ' 12 ',
  ' 13 ',
  ' 14 ',
  ' 15 ',
  ' 16 ',
  ' 17 ',
  ' 18 ',
  ' 19 ',
  ' 20 ',
  ' 21 ',
  ' 22 ',
  ' 23 ',
  ' 24 ',
  ' 25 ',
  ' 26 ',
  ' 27 ',
  ' 28 ',
  ' 29 ',
  ' 30 ',
  ' 31 ',
  ' 32 ',
  ' 33 ',
  ' 34 ',
  ' 35 ',
  ' 36 ',
  ' 37 ',
  ' 38 ',
  ' 39 ',
  ' 40 ',
  ' 41 ',
  ' 42 ',
  ' 43 ',
  ' 44 ',
  ' 45 ',
  ' 46 ',
  ' 47 ',
  ' 48 ',
  ' 49 ',
  ' 50 ',
  ' 51 ',
  ' 52 ',
  ' 53 ',
  ' 54 ',
  ' 55 ',
  ' 56 ',
  ' 57 ',
  ' 58 ',
  ' 59 ',
  ' 60 ',
  ' 61 ',
  ' 62 ',
  ' 63 ',
  ' 64 ',
  ' 65 ',
  ' 66 ',
  ' 67 ',
  ' 68 ',
  ' 69 ',
  ' 70 ',
  ' 71 ',
  ' 72 ',
  ' 73 ',
  ' 74 ',
  ' 75 ',
  ' 76 ',
  ' 77 ',
  ' 78 ',
  ' 79 ',
  ' 80 ',
  ' 81 ',
  ' 82 ',
  ' 83 ',
  ' 84 ',
  ' 85 ',
  ' 86 ',
  ' 87 ',
  ' 88 ',
  ' 89 ',
  ' 90 ',
  ' 91 ',
  ' 92 ',
  ' 93 ',
  ' 94 ',
  ' 95 ',
  ' 96 ',
  ' 97 ',
  ' 98 ',
  ' 99 ',
  ' 100 ',
  ' 101 ',
  ' 102 ',
  ' 103 ',
  ' 104 ',
  ' 105 ',
  ' 106 ',
  ' 107 ',
  ' 108 ',
  ' 109 ',
  ' 110 ',
  ' 111 ',
  ' 112 ',
  ' 113 ',
  ' 114 ',
  ' 115 ',
  ' 116 ',
  ' 117 ',
  ' 118 ',
  ' 119 ',
  ' 120 ',
  ' 121 ',
  ' 122 ',
  ' 123 ',
  ' 124 ',
  ' 125 ',
  ' 126 ',
  ' 127 ',
  ' 128 ',
  ' 129 ',
  ' 130 ',
  ' 131 ',
  ' 132 ',
  ' 133 ',
  ' 134 ',
  ' 135 ',
  ' 136 ',
  ' 137 ',
  ' 138 ',
  ' 139 ',
  ' 140 ',
  ' 141 ',
  ' 142 ',
  ' 143 ',
  ' 144 ',
  ' 145 ',
  ' 146 ',
  ' 147 ',
  ' 148 ',
  ' 149 ',
  ' 150 ',
  ' 151 ',
  ' 152 ',
  ' 153 ',
  ' 154 ',
  ' 155 ',
  ' 156 ',
  ' 157 ',
  ' 158 ',
  ' 159 ',
  ' 160 ',
  ' 161 ',
  ' 162 ',
  ' 163 ',
  ' 164 ',
  ' 165 ',
  ' 166 ',
  ' 167 ',
  ' 168 ',
  ' 169 ',
  ' 170 ',
  ' 171 ',
  ' 172 ',
  ' 173 ',
  ' 174 ',
  ' 175 ',
  ' 176 ',
  ' 177 ',
  ' 178 ',
  ' 179 ',
  ' 180 ',
  ' 181 ',
  ' 182 ',
  ' 183 ',
  ' 184 ',
  ' 185 ',
  ' 186 ',
  ' 187 ',
  ' 188 ',
  ' 189 ',
  ' 190 ',
  ' 191 ',
  ' 192 ',
  ' 193 ',
  ' 194 ',
  ' 195 ',
  ' 196 ',
  ' 197 ',
  ' 198 ',
  ' 199 ',
  ' 200 ',
  ' 201 ',
  ' 202 ',
  ' 203 ',
  ' 204 ',
  ' 205 ',
  ' 206 ',
  ' 207 ',
  ' 208 ',
  ' 209 ',
  ' 210 ',
  ' 211 ',
  ' 212 ',
  ' 213 ',
  ' 214 ',
  ' 215 ',
  ' 216 ',
  ' 217 ',
  ' 218 ',
  ' 219 ',
  ' 220 ',
  ' 221 ',
  ' 222 ',
  ' 223 ',
  ' 224 ',
  ' 225 ',
  ' 226 ',
  ' 227 ',
  ' 228 ',
  ' 229 ',
  ' 230 ',
  ' 231 ',
  ' 232 ',
  ' 233 '],
 'Country': ['  India  ',
  '  China  ',
  '  United States  ',
  '  Indonesia  ',
  '  Pakistan  ',
  '  Nigeria  ',
  '  Brazil  ',
  '  Bangladesh  ',
  '  Russia  ',
  '  Ethiopia  ',
  '  Mexico  ',
  '  Japan  ',
  '  Egypt  ',
  '  Philippines  ',
  '  DR Congo  ',
  '  Vietnam  ',
  '  Iran  ',
  '  Turkey  ',
  '  Germany  ',
  '  Thailand  ',
  '  Tanzania  ',
  '  United Kingdom  ',
  '  France  ',
  '  South Africa  ',
  '  Italy  ',
  '  Kenya  ',
  '  Myanmar  ',
  '  Colombia  ',
  '  South Korea  ',
  '  Sudan  ',
  '  Uganda  ',
  '  Spain  ',
  '  Algeria  ',
  '  Iraq  ',
  '  Argentina  ',
  '  Afghanistan  ',
  '  Yemen  ',
  '  Canada  ',
  '  Angola  ',
  '  Ukraine  ',
  '  Morocco  ',
  '  Poland  ',
  '  Uzbekistan  ',
  '  Malaysia  ',
  '  Mozambique  ',
  '  Ghana  ',
  '  Peru  ',
  '  Saudi Arabia  ',
  '  Madagascar  ',
  "  Côte d'Ivoire  ",
  '  Cameroon  ',
  '  Nepal  ',
  '  Venezuela  ',
  '  Niger  ',
  '  Australia  ',
  '  North Korea  ',
  '  Syria  ',
  '  Mali  ',
  '  Burkina Faso  ',
  '  Sri Lanka  ',
  '  Taiwan  ',
  '  Malawi  ',
  '  Zambia  ',
  '  Chad  ',
  '  Kazakhstan  ',
  '  Chile  ',
  '  Somalia  ',
  '  Senegal  ',
  '  Romania  ',
  '  Guatemala  ',
  '  Netherlands  ',
  '  Ecuador  ',
  '  Cambodia  ',
  '  Zimbabwe  ',
  '  Guinea  ',
  '  Benin  ',
  '  Rwanda  ',
  '  Burundi  ',
  '  Bolivia  ',
  '  Tunisia  ',
  '  South Sudan  ',
  '  Haiti  ',
  '  Belgium  ',
  '  Jordan  ',
  '  Dominican Republic  ',
  '  United Arab Emirates  ',
  '  Honduras  ',
  '  Cuba  ',
  '  Tajikistan  ',
  '  Papua New Guinea  ',
  '  Sweden  ',
  '  Czech Republic (Czechia)  ',
  '  Portugal  ',
  '  Azerbaijan  ',
  '  Greece  ',
  '  Togo  ',
  '  Hungary  ',
  '  Israel  ',
  '  Austria  ',
  '  Belarus  ',
  '  Switzerland  ',
  '  Sierra Leone  ',
  '  Laos  ',
  '  Turkmenistan  ',
  '  Libya  ',
  '  Hong Kong  ',
  '  Kyrgyzstan  ',
  '  Paraguay  ',
  '  Nicaragua  ',
  '  Bulgaria  ',
  '  Serbia  ',
  '  Congo  ',
  '  El Salvador  ',
  '  Denmark  ',
  '  Singapore  ',
  '  Lebanon  ',
  '  Liberia  ',
  '  Finland  ',
  '  Norway  ',
  '  State of Palestine  ',
  '  Central African Republic  ',
  '  Oman  ',
  '  Slovakia  ',
  '  Mauritania  ',
  '  Ireland  ',
  '  New Zealand  ',
  '  Costa Rica  ',
  '  Kuwait  ',
  '  Panama  ',
  '  Croatia  ',
  '  Georgia  ',
  '  Eritrea  ',
  '  Mongolia  ',
  '  Uruguay  ',
  '  Puerto Rico  ',
  '  Bosnia and Herzegovina  ',
  '  Qatar  ',
  '  Namibia  ',
  '  Moldova  ',
  '  Armenia  ',
  '  Jamaica  ',
  '  Lithuania  ',
  '  Gambia  ',
  '  Albania  ',
  '  Gabon  ',
  '  Botswana  ',
  '  Lesotho  ',
  '  Guinea-Bissau  ',
  '  Slovenia  ',
  '  Equatorial Guinea  ',
  '  Latvia  ',
  '  North Macedonia  ',
  '  Bahrain  ',
  '  Trinidad and Tobago  ',
  '  Timor-Leste  ',
  '  Cyprus  ',
  '  Estonia  ',
  '  Mauritius  ',
  '  Eswatini  ',
  '  Djibouti  ',
  '  Fiji  ',
  '  Comoros  ',
  '  Réunion  ',
  '  Solomon Islands  ',
  '  Guyana  ',
  '  Bhutan  ',
  '  Macao  ',
  '  Luxembourg  ',
  '  Suriname  ',
  '  Montenegro  ',
  '  Western Sahara  ',
  '  Malta  ',
  '  Maldives  ',
  '  Cabo Verde  ',
  '  Brunei   ',
  '  Belize  ',
  '  Bahamas  ',
  '  Iceland  ',
  '  Guadeloupe  ',
  '  Martinique  ',
  '  Mayotte  ',
  '  Vanuatu  ',
  '  French Guiana  ',
  '  New Caledonia  ',
  '  Barbados  ',
  '  French Polynesia  ',
  '  Sao Tome & Principe  ',
  '  Samoa  ',
  '  Curaçao  ',
  '  Saint Lucia  ',
  '  Guam  ',
  '  Kiribati  ',
  '  Seychelles  ',
  '  Grenada  ',
  '  Micronesia  ',
  '  Aruba  ',
  '  Tonga  ',
  '  St. Vincent & Grenadines  ',
  '  Antigua and Barbuda  ',
  '  U.S. Virgin Islands  ',
  '  Isle of Man  ',
  '  Andorra  ',
  '  Cayman Islands  ',
  '  Dominica  ',
  '  Bermuda  ',
  '  Faeroe Islands  ',
  '  Greenland  ',
  '  Saint Kitts & Nevis  ',
  '  Turks and Caicos  ',
  '  American Samoa  ',
  '  Sint Maarten  ',
  '  Northern Mariana Islands  ',
  '  Liechtenstein  ',
  '  Gibraltar  ',
  '  British Virgin Islands  ',
  '  Monaco  ',
  '  Marshall Islands  ',
  '  San Marino  ',
  '  Caribbean Netherlands  ',
  '  Palau  ',
  '  Anguilla  ',
  '  Cook Islands  ',
  '  Nauru  ',
  '  Saint Barthelemy  ',
  '  Wallis & Futuna  ',
  '  Tuvalu  ',
  '  Saint Pierre & Miquelon  ',
  '  Saint Helena  ',
  '  Montserrat  ',
  '  Falkland Islands  ',
  '  Tokelau  ',
  '  Niue  ',
  '  Holy See  '],
 'Population2025': [' 1,463,865,525 ',
  ' 1,416,096,094 ',
  ' 347,275,807 ',
  ' 285,721,236 ',
  ' 255,219,554 ',
  ' 237,527,782 ',
  ' 212,812,405 ',
  ' 175,686,899 ',
  ' 143,997,393 ',
  ' 135,472,051 ',
  ' 131,946,900 ',
  ' 123,103,479 ',
  ' 118,365,995 ',
  ' 116,786,962 ',
  ' 112,832,473 ',
  ' 101,598,527 ',
  ' 92,417,681 ',
  ' 87,685,426 ',
  ' 84,075,075 ',
  ' 71,619,863 ',
  ' 70,545,865 ',
  ' 69,551,332 ',
  ' 66,650,804 ',
  ' 64,747,319 ',
  ' 59,146,260 ',
  ' 57,532,493 ',
  ' 54,850,648 ',
  ' 53,425,635 ',
  ' 51,667,029 ',
  ' 51,662,147 ',
  ' 51,384,894 ',
  ' 47,889,958 ',
  ' 47,435,312 ',
  ' 47,020,774 ',
  ' 45,851,378 ',
  ' 43,844,111 ',
  ' 41,773,878 ',
  ' 40,126,723 ',
  ' 39,040,039 ',
  ' 38,980,376 ',
  ' 38,430,770 ',
  ' 38,140,910 ',
  ' 37,053,428 ',
  ' 35,977,838 ',
  ' 35,631,653 ',
  ' 35,064,272 ',
  ' 34,576,665 ',
  ' 34,566,328 ',
  ' 32,740,678 ',
  ' 32,711,547 ',
  ' 29,879,337 ',
  ' 29,618,118 ',
  ' 28,516,896 ',
  ' 27,917,831 ',
  ' 26,974,026 ',
  ' 26,571,036 ',
  ' 25,620,427 ',
  ' 25,198,821 ',
  ' 24,074,580 ',
  ' 23,229,470 ',
  ' 23,112,793 ',
  ' 22,216,120 ',
  ' 21,913,874 ',
  ' 21,003,705 ',
  ' 20,843,754 ',
  ' 19,859,921 ',
  ' 19,654,739 ',
  ' 18,931,966 ',
  ' 18,908,650 ',
  ' 18,687,881 ',
  ' 18,346,819 ',
  ' 18,289,896 ',
  ' 17,847,982 ',
  ' 16,950,795 ',
  ' 15,099,727 ',
  ' 14,814,460 ',
  ' 14,569,341 ',
  ' 14,390,003 ',
  ' 12,581,843 ',
  ' 12,348,573 ',
  ' 12,188,788 ',
  ' 11,906,095 ',
  ' 11,758,603 ',
  ' 11,520,684 ',
  ' 11,520,487 ',
  ' 11,346,000 ',
  ' 11,005,850 ',
  ' 10,937,203 ',
  ' 10,786,734 ',
  ' 10,762,817 ',
  ' 10,656,633 ',
  ' 10,609,239 ',
  ' 10,411,834 ',
  ' 10,397,713 ',
  ' 9,938,844 ',
  ' 9,721,608 ',
  ' 9,632,287 ',
  ' 9,517,181 ',
  ' 9,113,574 ',
  ' 8,997,603 ',
  ' 8,967,407 ',
  ' 8,819,794 ',
  ' 7,873,046 ',
  ' 7,618,847 ',
  ' 7,458,555 ',
  ' 7,396,076 ',
  ' 7,295,034 ',
  ' 7,013,078 ',
  ' 7,007,502 ',
  ' 6,714,560 ',
  ' 6,689,039 ',
  ' 6,484,437 ',
  ' 6,365,503 ',
  ' 6,002,507 ',
  ' 5,870,750 ',
  ' 5,849,421 ',
  ' 5,731,206 ',
  ' 5,623,329 ',
  ' 5,623,071 ',
  ' 5,589,623 ',
  ' 5,513,282 ',
  ' 5,494,691 ',
  ' 5,474,881 ',
  ' 5,315,065 ',
  ' 5,308,039 ',
  ' 5,251,899 ',
  ' 5,152,950 ',
  ' 5,026,078 ',
  ' 4,571,189 ',
  ' 3,848,160 ',
  ' 3,806,671 ',
  ' 3,607,003 ',
  ' 3,517,100 ',
  ' 3,384,688 ',
  ' 3,235,289 ',
  ' 3,140,095 ',
  ' 3,115,889 ',
  ' 3,092,816 ',
  ' 2,996,106 ',
  ' 2,952,365 ',
  ' 2,837,077 ',
  ' 2,830,144 ',
  ' 2,822,093 ',
  ' 2,771,508 ',
  ' 2,593,130 ',
  ' 2,562,122 ',
  ' 2,363,325 ',
  ' 2,249,515 ',
  ' 2,117,072 ',
  ' 1,938,431 ',
  ' 1,853,559 ',
  ' 1,813,791 ',
  ' 1,643,332 ',
  ' 1,511,155 ',
  ' 1,418,517 ',
  ' 1,370,754 ',
  ' 1,344,232 ',
  ' 1,268,280 ',
  ' 1,256,174 ',
  ' 1,184,076 ',
  ' 933,154 ',
  ' 882,847 ',
  ' 882,405 ',
  ' 838,645 ',
  ' 835,986 ',
  ' 796,682 ',
  ' 722,007 ',
  ' 680,453 ',
  ' 639,850 ',
  ' 632,729 ',
  ' 600,904 ',
  ' 545,405 ',
  ' 529,676 ',
  ' 527,326 ',
  ' 466,330 ',
  ' 422,924 ',
  ' 403,033 ',
  ' 398,266 ',
  ' 373,791 ',
  ' 340,439 ',
  ' 337,011 ',
  ' 335,169 ',
  ' 313,666 ',
  ' 295,333 ',
  ' 282,623 ',
  ' 282,465 ',
  ' 240,254 ',
  ' 219,306 ',
  ' 185,487 ',
  ' 180,149 ',
  ' 168,999 ',
  ' 136,488 ',
  ' 132,779 ',
  ' 117,303 ',
  ' 113,683 ',
  ' 108,147 ',
  ' 103,742 ',
  ' 99,924 ',
  ' 94,209 ',
  ' 84,138 ',
  ' 84,118 ',
  ' 82,904 ',
  ' 75,844 ',
  ' 65,871 ',
  ' 64,555 ',
  ' 56,002 ',
  ' 55,745 ',
  ' 46,922 ',
  ' 46,855 ',
  ' 46,029 ',
  ' 43,923 ',
  ' 43,541 ',
  ' 40,128 ',
  ' 40,126 ',
  ' 39,732 ',
  ' 38,341 ',
  ' 36,282 ',
  ' 33,572 ',
  ' 31,338 ',
  ' 17,663 ',
  ' 14,728 ',
  ' 13,263 ',
  ' 12,025 ',
  ' 11,414 ',
  ' 11,194 ',
  ' 9,492 ',
  ' 5,574 ',
  ' 5,197 ',
  ' 4,359 ',
  ' 3,469 ',
  ' 2,608 ',
  ' 1,821 ',
  ' 501 '],
 'Yearly_change': [' 0.89% ',
  ' −0.23% ',
  ' 0.54% ',
  ' 0.79% ',
  ' 1.57% ',
  ' 2.08% ',
  ' 0.38% ',
  ' 1.22% ',
  ' −0.57% ',
  ' 2.58% ',
  ' 0.83% ',
  ' −0.52% ',
  ' 1.57% ',
  ' 0.81% ',
  ' 3.25% ',
  ' 0.6% ',
  ' 0.93% ',
  ' 0.24% ',
  ' −0.56% ',
  ' −0.07% ',
  ' 2.9% ',
  ' 0.6% ',
  ' 0.15% ',
  ' 1.16% ',
  ' −0.33% ',
  ' 1.95% ',
  ' 0.64% ',
  ' 1.02% ',
  ' −0.1% ',
  ' 2.4% ',
  ' 2.74% ',
  ' −0.04% ',
  ' 1.33% ',
  ' 2.13% ',
  ' 0.34% ',
  ' 2.81% ',
  ' 2.93% ',
  ' 0.97% ',
  ' 3.05% ',
  ' 2.96% ',
  ' 0.92% ',
  ' −1.03% ',
  ' 1.9% ',
  ' 1.18% ',
  ' 2.89% ',
  ' 1.85% ',
  ' 1.05% ',
  ' 1.78% ',
  ' 2.43% ',
  ' 2.43% ',
  ' 2.59% ',
  ' −0.11% ',
  ' 0.39% ',
  ' 3.28% ',
  ' 0.98% ',
  ' 0.27% ',
  ' 3.84% ',
  ' 2.94% ',
  ' 2.23% ',
  ' 0.54% ',
  ' −0.44% ',
  ' 2.59% ',
  ' 2.81% ',
  ' 3.47% ',
  ' 1.22% ',
  ' 0.48% ',
  ' 3.4% ',
  ' 2.32% ',
  ' −0.56% ',
  ' 1.53% ',
  ' 0.65% ',
  ' 0.85% ',
  ' 1.19% ',
  ' 1.9% ',
  ' 2.34% ',
  ' 2.43% ',
  ' 2.19% ',
  ' 2.44% ',
  ' 1.36% ',
  ' 0.58% ',
  ' 2.05% ',
  ' 1.13% ',
  ' 0.17% ',
  ' −0.28% ',
  ' 0.81% ',
  ' 2.89% ',
  ' 1.66% ',
  ' −0.39% ',
  ' 1.85% ',
  ' 1.76% ',
  ' 0.47% ',
  ' −1.18% ',
  ' −0.13% ',
  ' 0.59% ',
  ' −1.08% ',
  ' 2.17% ',
  ' −0.45% ',
  ' 1.39% ',
  ' −0.08% ',
  ' −0.65% ',
  ' 0.51% ',
  ' 2.06% ',
  ' 1.33% ',
  ' 1.66% ',
  ' 1.05% ',
  ' −0.25% ',
  ' 1.52% ',
  ' 1.21% ',
  ' 1.32% ',
  ' −0.64% ',
  ' −0.7% ',
  ' 2.39% ',
  ' 0.43% ',
  ' 0.42% ',
  ' 0.66% ',
  ' 0.75% ',
  ' 2.11% ',
  ' 0.11% ',
  ' 0.83% ',
  ' 1.71% ',
  ' 3.43% ',
  ' 4.04% ',
  ' −0.58% ',
  ' 2.82% ',
  ' 1.01% ',
  ' 0.73% ',
  ' 0.45% ',
  ' 1.86% ',
  ' 1.23% ',
  ' −0.7% ',
  ' −0.03% ',
  ' 2.02% ',
  ' 1.2% ',
  ' −0.06% ',
  ' −0.21% ',
  ' −0.76% ',
  ' 2.21% ',
  ' 2.07% ',
  ' −1.28% ',
  ' −0.72% ',
  ' −0.07% ',
  ' −1.01% ',
  ' 2.25% ',
  ' −0.73% ',
  ' 2.13% ',
  ' 1.63% ',
  ' 1.11% ',
  ' 2.19% ',
  ' −0.08% ',
  ' 2.43% ',
  ' −0.98% ',
  ' −0.51% ',
  ' 2.26% ',
  ' 0.22% ',
  ' 1.28% ',
  ' 0.92% ',
  ' −1.2% ',
  ' −0.23% ',
  ' 1.07% ',
  ' 1.31% ',
  ' 0.47% ',
  ' 1.87% ',
  ' 0.43% ',
  ' 2.37% ',
  ' 0.59% ',
  ' 0.65% ',
  ' 0.24% ',
  ' 1.1% ',
  ' 0.85% ',
  ' −0.9% ',
  ' 1.76% ',
  ' 1.07% ',
  ' 0.36% ',
  ' 0.47% ',
  ' 0.78% ',
  ' 1.4% ',
  ' 0.44% ',
  ' 1.24% ',
  ' −0.35% ',
  ' −0.8% ',
  ' 3.22% ',
  ' 2.26% ',
  ' 1.67% ',
  ' 0.92% ',
  ' 0.06% ',
  ' 0.23% ',
  ' 2% ',
  ' 0.59% ',
  ' 0% ',
  ' 0.23% ',
  ' 0.73% ',
  ' 1.46% ',
  ' 1.81% ',
  ' 0.08% ',
  ' 0.46% ',
  ' 0.07% ',
  ' −0.42% ',
  ' −0.69% ',
  ' 0.47% ',
  ' −0.9% ',
  ' −0.05% ',
  ' 1.18% ',
  ' 1.86% ',
  ' −0.5% ',
  ' −0.13% ',
  ' 1.09% ',
  ' −0.17% ',
  ' 0.17% ',
  ' 0.69% ',
  ' −1.57% ',
  ' 1.32% ',
  ' −1.66% ',
  ' 0.65% ',
  ' 2.03% ',
  ' 0.66% ',
  ' −0.75% ',
  ' −3.37% ',
  ' −0.03% ',
  ' 2.16% ',
  ' −0.18% ',
  ' 0.89% ',
  ' −3.39% ',
  ' 0.65% ',
  ' 1.39% ',
  ' −0.74% ',
  ' −1.6% ',
  ' −0.96% ',
  ' −0.76% ',
  ' −0.68% ',
  ' −0.03% ',
  ' 4.07% ',
  ' 0.11% ',
  ' 1.01% '],
 'Net_change': [' 12,929,734 ',
  ' −3,225,184 ',
  ' 1,849,236 ',
  ' 2,233,305 ',
  ' 3,950,390 ',
  ' 4,848,304 ',
  ' 813,832 ',
  ' 2,124,535 ',
  ' −823,030 ',
  ' 3,412,284 ',
  ' 1,085,893 ',
  ' −649,562 ',
  ' 1,827,737 ',
  ' 943,292 ',
  ' 3,556,208 ',
  ' 610,841 ',
  ' 849,943 ',
  ' 211,621 ',
  ' −477,167 ',
  ' −48,148 ',
  ' 1,985,708 ',
  ' 413,140 ',
  ' 102,274 ',
  ' 740,132 ',
  ' −196,607 ',
  ' 1,099,549 ',
  ' 350,557 ',
  ' 539,272 ',
  ' −50,561 ',
  ' 1,213,184 ',
  ' 1,369,802 ',
  ' −20,568 ',
  ' 621,004 ',
  ' 978,759 ',
  ' 155,219 ',
  ' 1,196,619 ',
  ' 1,190,714 ',
  ' 384,293 ',
  ' 1,154,190 ',
  ' 1,120,155 ',
  ' 349,597 ',
  ' −398,291 ',
  ' 691,569 ',
  ' 420,165 ',
  ' 999,887 ',
  ' 636,858 ',
  ' 358,817 ',
  ' 603,571 ',
  ' 775,722 ',
  ' 777,317 ',
  ' 755,593 ',
  ' −32,936 ',
  ' 111,353 ',
  ' 885,419 ',
  ' 260,821 ',
  ' 72,213 ',
  ' 947,667 ',
  ' 720,226 ',
  ' 525,799 ',
  ' 125,905 ',
  ' −101,169 ',
  ' 560,834 ',
  ' 598,918 ',
  ' 704,582 ',
  ' 251,183 ',
  ' 95,150 ',
  ' 645,588 ',
  ' 429,982 ',
  ' −106,438 ',
  ' 281,522 ',
  ' 118,077 ',
  ' 154,418 ',
  ' 209,181 ',
  ' 316,422 ',
  ' 344,942 ',
  ' 351,736 ',
  ' 312,774 ',
  ' 342,217 ',
  ' 168,528 ',
  ' 71,464 ',
  ' 245,380 ',
  ' 133,538 ',
  ' 19,840 ',
  ' −32,192 ',
  ' 92,930 ',
  ' 318,871 ',
  ' 180,147 ',
  ' −42,580 ',
  ' 195,807 ',
  ' 186,315 ',
  ' 49,634 ',
  ' −126,620 ',
  ' −13,458 ',
  ' 61,136 ',
  ' −108,973 ',
  ' 206,372 ',
  ' −43,848 ',
  ' 130,160 ',
  ' −7,239 ',
  ' −59,093 ',
  ' 45,426 ',
  ' 177,772 ',
  ' 103,227 ',
  ' 124,349 ',
  ' 77,532 ',
  ' −18,833 ',
  ' 109,025 ',
  ' 83,925 ',
  ' 91,362 ',
  ' −43,129 ',
  ' −47,177 ',
  ' 151,476 ',
  ' 27,310 ',
  ' 25,095 ',
  ' 38,363 ',
  ' 43,459 ',
  ' 118,389 ',
  ' 6,019 ',
  ' 46,411 ',
  ' 94,180 ',
  ' 182,592 ',
  ' 213,153 ',
  ' −31,879 ',
  ' 145,670 ',
  ' 53,022 ',
  ' 37,955 ',
  ' 23,040 ',
  ' 91,571 ',
  ' 55,612 ',
  ' −27,165 ',
  ' −999 ',
  ' 71,400 ',
  ' 41,560 ',
  ' −1,900 ',
  ' −6,915 ',
  ' −24,158 ',
  ' 67,466 ',
  ' 62,685 ',
  ' −38,855 ',
  ' −21,475 ',
  ' −2,098 ',
  ' −28,966 ',
  ' 62,105 ',
  ' −20,257 ',
  ' 54,178 ',
  ' 40,983 ',
  ' 25,902 ',
  ' 48,163 ',
  ' −1,625 ',
  ' 45,915 ',
  ' −18,312 ',
  ' −9,218 ',
  ' 36,283 ',
  ' 3,373 ',
  ' 17,879 ',
  ' 12,472 ',
  ' −16,314 ',
  ' −2,889 ',
  ' 13,352 ',
  ' 15,354 ',
  ' 4,370 ',
  ' 16,219 ',
  ' 3,814 ',
  ' 19,447 ',
  ' 4,899 ',
  ' 5,158 ',
  ' 1,745 ',
  ' 7,417 ',
  ' 5,419 ',
  ' −5,750 ',
  ' 10,398 ',
  ' 5,798 ',
  ' 1,877 ',
  ' 2,449 ',
  ' 3,609 ',
  ' 5,852 ',
  ' 1,750 ',
  ' 4,870 ',
  ' −1,315 ',
  ' −2,756 ',
  ' 10,506 ',
  ' 7,392 ',
  ' 5,144 ',
  ' 2,694 ',
  ' 156 ',
  ' 658 ',
  ' 4,718 ',
  ' 1,287 ',
  ' 5 ',
  ' 405 ',
  ' 1,222 ',
  ' 1,970 ',
  ' 2,361 ',
  ' 96 ',
  ' 523 ',
  ' 81 ',
  ' −433 ',
  ' −692 ',
  ' 437 ',
  ' −767 ',
  ' −42 ',
  ' 966 ',
  ' 1,387 ',
  ' −334 ',
  ' −81 ',
  ' 602 ',
  ' −95 ',
  ' 79 ',
  ' 320 ',
  ' −736 ',
  ' 573 ',
  ' −737 ',
  ' 258 ',
  ' 797 ',
  ' 261 ',
  ' −290 ',
  ' −1,266 ',
  ' −9 ',
  ' 663 ',
  ' −32 ',
  ' 130 ',
  ' −466 ',
  ' 78 ',
  ' 156 ',
  ' −83 ',
  ' −154 ',
  ' −54 ',
  ' −40 ',
  ' −30 ',
  ' −1 ',
  ' 102 ',
  ' 2 ',
  ' 5 '],
 'Density': [' 492 ',
  ' 151 ',
  ' 38 ',
  ' 158 ',
  ' 331 ',
  ' 261 ',
  ' 25 ',
  ' 1,350 ',
  ' 9 ',
  ' 135 ',
  ' 68 ',
  ' 338 ',
  ' 119 ',
  ' 392 ',
  ' 50 ',
  ' 328 ',
  ' 57 ',
  ' 114 ',
  ' 241 ',
  ' 140 ',
  ' 80 ',
  ' 287 ',
  ' 122 ',
  ' 53 ',
  ' 201 ',
  ' 101 ',
  ' 84 ',
  ' 48 ',
  ' 531 ',
  ' 29 ',
  ' 257 ',
  ' 96 ',
  ' 20 ',
  ' 108 ',
  ' 17 ',
  ' 67 ',
  ' 79 ',
  ' 4 ',
  ' 31 ',
  ' 67 ',
  ' 86 ',
  ' 125 ',
  ' 87 ',
  ' 110 ',
  ' 45 ',
  ' 154 ',
  ' 27 ',
  ' 16 ',
  ' 56 ',
  ' 103 ',
  ' 63 ',
  ' 207 ',
  ' 32 ',
  ' 22 ',
  ' 4 ',
  ' 221 ',
  ' 140 ',
  ' 21 ',
  ' 88 ',
  ' 370 ',
  ' 653 ',
  ' 236 ',
  ' 29 ',
  ' 17 ',
  ' 8 ',
  ' 27 ',
  ' 31 ',
  ' 98 ',
  ' 82 ',
  ' 174 ',
  ' 544 ',
  ' 74 ',
  ' 101 ',
  ' 44 ',
  ' 61 ',
  ' 131 ',
  ' 591 ',
  ' 560 ',
  ' 12 ',
  ' 79 ',
  ' 20 ',
  ' 432 ',
  ' 388 ',
  ' 130 ',
  ' 238 ',
  ' 136 ',
  ' 98 ',
  ' 103 ',
  ' 77 ',
  ' 24 ',
  ' 26 ',
  ' 137 ',
  ' 114 ',
  ' 126 ',
  ' 77 ',
  ' 179 ',
  ' 106 ',
  ' 440 ',
  ' 111 ',
  ' 44 ',
  ' 227 ',
  ' 122 ',
  ' 34 ',
  ' 16 ',
  ' 4 ',
  ' 7,044 ',
  ' 38 ',
  ' 18 ',
  ' 58 ',
  ' 62 ',
  ' 76 ',
  ' 19 ',
  ' 307 ',
  ' 141 ',
  ' 8,387 ',
  ' 572 ',
  ' 60 ',
  ' 19 ',
  ' 15 ',
  ' 929 ',
  ' 9 ',
  ' 18 ',
  ' 114 ',
  ' 5 ',
  ' 77 ',
  ' 20 ',
  ' 101 ',
  ' 282 ',
  ' 61 ',
  ' 69 ',
  ' 55 ',
  ' 36 ',
  ' 2 ',
  ' 19 ',
  ' 365 ',
  ' 62 ',
  ' 268 ',
  ' 4 ',
  ' 91 ',
  ' 104 ',
  ' 262 ',
  ' 45 ',
  ' 279 ',
  ' 101 ',
  ' 10 ',
  ' 5 ',
  ' 78 ',
  ' 80 ',
  ' 105 ',
  ' 69 ',
  ' 30 ',
  ' 72 ',
  ' 2,162 ',
  ' 295 ',
  ' 95 ',
  ' 148 ',
  ' 32 ',
  ' 625 ',
  ' 73 ',
  ' 51 ',
  ' 51 ',
  ' 474 ',
  ' 353 ',
  ' 30 ',
  ' 4 ',
  ' 21 ',
  ' 24,067 ',
  ' 263 ',
  ' 4 ',
  ' 47 ',
  ' 2 ',
  ' 1,704 ',
  ' 1,766 ',
  ' 131 ',
  ' 88 ',
  ' 19 ',
  ' 40 ',
  ' 4 ',
  ' 221 ',
  ' 321 ',
  ' 899 ',
  ' 27 ',
  ' 4 ',
  ' 16 ',
  ' 657 ',
  ' 77 ',
  ' 250 ',
  ' 77 ',
  ' 418 ',
  ' 295 ',
  ' 313 ',
  ' 169 ',
  ' 289 ',
  ' 345 ',
  ' 162 ',
  ' 601 ',
  ' 144 ',
  ' 256 ',
  ' 214 ',
  ' 240 ',
  ' 148 ',
  ' 176 ',
  ' 316 ',
  ' 88 ',
  ' 1,291 ',
  ' 40 ',
  ' 0 ',
  ' 180 ',
  ' 49 ',
  ' 230 ',
  ' 1,292 ',
  ' 95 ',
  ' 251 ',
  ' 4,013 ',
  ' 265 ',
  ' 25,732 ',
  ' 202 ',
  ' 560 ',
  ' 96 ',
  ' 38 ',
  ' 164 ',
  ' 55 ',
  ' 601 ',
  ' 544 ',
  ' 80 ',
  ' 316 ',
  ' 24 ',
  ' 13 ',
  ' 44 ',
  ' 0 ',
  ' 261 ',
  ' 7 ',
  ' 1,253 '],
 'Land_area': [' 2,973,190 ',
  ' 9,388,211 ',
  ' 9,147,420 ',
  ' 1,811,570 ',
  ' 770,880 ',
  ' 910,770 ',
  ' 8,358,140 ',
  ' 130,170 ',
  ' 16,376,870 ',
  ' 1,000,000 ',
  ' 1,943,950 ',
  ' 364,555 ',
  ' 995,450 ',
  ' 298,170 ',
  ' 2,267,050 ',
  ' 310,070 ',
  ' 1,628,550 ',
  ' 769,630 ',
  ' 348,560 ',
  ' 510,890 ',
  ' 885,800 ',
  ' 241,930 ',

In [152]:
import pandas as pd
import numpy as np
Population_Summary=pd.DataFrame(Data)

In [153]:
Population_Summary

,Sr_no,Country,Population2025,Yearly_change,Net_change,Density,Land_area,Migrants,Fert_rate,Median_age,Urban_pop,World_share
0,1,India,"1,463,865,525",0.89%,"12,929,734",492,"2,973,190","−495,753",1.94,28.8,37.1%,17.78%
1,2,China,"1,416,096,094",−0.23%,"−3,225,184",151,"9,388,211","−268,126",1.02,40.1,67.5%,17.20%
2,3,United States,"347,275,807",0.54%,"1,849,236",38,"9,147,420","1,230,663",1.62,38.5,82.8%,4.22%
3,4,Indonesia,"285,721,236",0.79%,"2,233,305",158,"1,811,570","−39,509",2.1,30.4,59.6%,3.47%
4,5,Pakistan,"255,219,554",1.57%,"3,950,390",331,"770,880","−1,235,336",3.5,20.6,34.4%,3.10%
...,...,...,...,...,...,...,...,...,...,...,...,...
228,229,Montserrat,"4,359",−0.68%,−30,44,100,−9,1.45,41.6,11.5%,0.000053%
229,230,Falkland Islands,"3,469",−0.03%,−1,0,"12,170",−17,1.7,42.8,68%,0.000042%
230,231,Tokelau,"2,608",4.07%,102,261,10,53,2.57,27.3,,0.000032%
231,232,Niue,"1,821",0.11%,2,7,260,3,2.46,35.7,44.5%,0.000022%
232,233,Holy See,501,1.01%,5,"1,253",0,13,1,57.4,,0.0000061%

Data Cleaning

In [154]:
Population_Summary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233 entries, 0 to 232
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Sr_no           233 non-null    object
 1   Country         233 non-null    object
 2   Population2025  233 non-null    object
 3   Yearly_change   233 non-null    object
 4   Net_change      233 non-null    object
 5   Density         233 non-null    object
 6   Land_area       233 non-null    object
 7   Migrants        233 non-null    object
 8   Fert_rate       233 non-null    object
 9   Median_age      233 non-null    object
 10  Urban_pop       233 non-null    object
 11  World_share     233 non-null    object
dtypes: object(12)
memory usage: 22.0+ KB

In [155]:
Population_Summary.isnull().sum()

Sr_no             0
Country           0
Population2025    0
Yearly_change     0
Net_change        0
Density           0
Land_area         0
Migrants          0
Fert_rate         0
Median_age        0
Urban_pop         0
World_share       0
dtype: int64

In [156]:
Population_Summary=Population_Summary.drop(['Sr_no'],axis=1)

In [157]:
Population_Summary

,Country,Population2025,Yearly_change,Net_change,Density,Land_area,Migrants,Fert_rate,Median_age,Urban_pop,World_share
0,India,"1,463,865,525",0.89%,"12,929,734",492,"2,973,190","−495,753",1.94,28.8,37.1%,17.78%
1,China,"1,416,096,094",−0.23%,"−3,225,184",151,"9,388,211","−268,126",1.02,40.1,67.5%,17.20%
2,United States,"347,275,807",0.54%,"1,849,236",38,"9,147,420","1,230,663",1.62,38.5,82.8%,4.22%
3,Indonesia,"285,721,236",0.79%,"2,233,305",158,"1,811,570","−39,509",2.1,30.4,59.6%,3.47%
4,Pakistan,"255,219,554",1.57%,"3,950,390",331,"770,880","−1,235,336",3.5,20.6,34.4%,3.10%
...,...,...,...,...,...,...,...,...,...,...,...
228,Montserrat,"4,359",−0.68%,−30,44,100,−9,1.45,41.6,11.5%,0.000053%
229,Falkland Islands,"3,469",−0.03%,−1,0,"12,170",−17,1.7,42.8,68%,0.000042%
230,Tokelau,"2,608",4.07%,102,261,10,53,2.57,27.3,,0.000032%
231,Niue,"1,821",0.11%,2,7,260,3,2.46,35.7,44.5%,0.000022%
232,Holy See,501,1.01%,5,"1,253",0,13,1,57.4,,0.0000061%

In [158]:
Population_Summary['Population2025']=Population_Summary['Population2025'].str.replace(',','')
Population_Summary['Population2025']=Population_Summary['Population2025'].astype('int')
Population_Summary

,Country,Population2025,Yearly_change,Net_change,Density,Land_area,Migrants,Fert_rate,Median_age,Urban_pop,World_share
0,India,1463865525,0.89%,"12,929,734",492,"2,973,190","−495,753",1.94,28.8,37.1%,17.78%
1,China,1416096094,−0.23%,"−3,225,184",151,"9,388,211","−268,126",1.02,40.1,67.5%,17.20%
2,United States,347275807,0.54%,"1,849,236",38,"9,147,420","1,230,663",1.62,38.5,82.8%,4.22%
3,Indonesia,285721236,0.79%,"2,233,305",158,"1,811,570","−39,509",2.1,30.4,59.6%,3.47%
4,Pakistan,255219554,1.57%,"3,950,390",331,"770,880","−1,235,336",3.5,20.6,34.4%,3.10%
...,...,...,...,...,...,...,...,...,...,...,...
228,Montserrat,4359,−0.68%,−30,44,100,−9,1.45,41.6,11.5%,0.000053%
229,Falkland Islands,3469,−0.03%,−1,0,"12,170",−17,1.7,42.8,68%,0.000042%
230,Tokelau,2608,4.07%,102,261,10,53,2.57,27.3,,0.000032%
231,Niue,1821,0.11%,2,7,260,3,2.46,35.7,44.5%,0.000022%
232,Holy See,501,1.01%,5,"1,253",0,13,1,57.4,,0.0000061%

In [159]:
Population_Summary['Yearly_change']=Population_Summary['Yearly_change'].str.replace('%','')
Population_Summary['Yearly_change']=Population_Summary['Yearly_change'].str.replace('−', '-')
Population_Summary['Yearly_change']=Population_Summary['Yearly_change'].str.strip()

In [160]:
Population_Summary['Yearly_change']=Population_Summary['Yearly_change'].astype('float')

In [161]:
Population_Summary

,Country,Population2025,Yearly_change,Net_change,Density,Land_area,Migrants,Fert_rate,Median_age,Urban_pop,World_share
0,India,1463865525,0.89,"12,929,734",492,"2,973,190","−495,753",1.94,28.8,37.1%,17.78%
1,China,1416096094,-0.23,"−3,225,184",151,"9,388,211","−268,126",1.02,40.1,67.5%,17.20%
2,United States,347275807,0.54,"1,849,236",38,"9,147,420","1,230,663",1.62,38.5,82.8%,4.22%
3,Indonesia,285721236,0.79,"2,233,305",158,"1,811,570","−39,509",2.1,30.4,59.6%,3.47%
4,Pakistan,255219554,1.57,"3,950,390",331,"770,880","−1,235,336",3.5,20.6,34.4%,3.10%
...,...,...,...,...,...,...,...,...,...,...,...
228,Montserrat,4359,-0.68,−30,44,100,−9,1.45,41.6,11.5%,0.000053%
229,Falkland Islands,3469,-0.03,−1,0,"12,170",−17,1.7,42.8,68%,0.000042%
230,Tokelau,2608,4.07,102,261,10,53,2.57,27.3,,0.000032%
231,Niue,1821,0.11,2,7,260,3,2.46,35.7,44.5%,0.000022%
232,Holy See,501,1.01,5,"1,253",0,13,1,57.4,,0.0000061%

In [162]:
Population_Summary['Net_change']=Population_Summary['Net_change'].str.replace(',','')
Population_Summary['Net_change']=Population_Summary['Net_change'].str.replace('%','')
Population_Summary['Net_change']=Population_Summary['Net_change'].str.replace('−','-')
Population_Summary['Net_change']=Population_Summary['Net_change'].astype(float)

Population_Summary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233 entries, 0 to 232
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country         233 non-null    object
 1   Population2025  233 non-null    int32
 2   Yearly_change   233 non-null    float64
 3   Net_change      233 non-null    float64
 4   Density         233 non-null    object
 5   Land_area       233 non-null    object
 6   Migrants        233 non-null    object
 7   Fert_rate       233 non-null    object
 8   Median_age      233 non-null    object
 9   Urban_pop       233 non-null    object
 10  World_share     233 non-null    object
dtypes: float64(2), int32(1), object(8)
memory usage: 19.2+ KB

In [163]:
Population_Summary['Density']=Population_Summary['Density'].str.replace(',','')
Population_Summary['Density']=Population_Summary['Density'].astype(float)
Population_Summary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233 entries, 0 to 232
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country         233 non-null    object
 1   Population2025  233 non-null    int32
 2   Yearly_change   233 non-null    float64
 3   Net_change      233 non-null    float64
 4   Density         233 non-null    float64
 5   Land_area       233 non-null    object
 6   Migrants        233 non-null    object
 7   Fert_rate       233 non-null    object
 8   Median_age      233 non-null    object
 9   Urban_pop       233 non-null    object
 10  World_share     233 non-null    object
dtypes: float64(3), int32(1), object(7)
memory usage: 19.2+ KB

In [164]:
Population_Summary['Land_area']=Population_Summary['Land_area'].str.replace(',','')
Population_Summary['Land_area']=Population_Summary['Land_area'].astype(float)
Population_Summary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233 entries, 0 to 232
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country         233 non-null    object
 1   Population2025  233 non-null    int32
 2   Yearly_change   233 non-null    float64
 3   Net_change      233 non-null    float64
 4   Density         233 non-null    float64
 5   Land_area       233 non-null    float64
 6   Migrants        233 non-null    object
 7   Fert_rate       233 non-null    object
 8   Median_age      233 non-null    object
 9   Urban_pop       233 non-null    object
 10  World_share     233 non-null    object
dtypes: float64(4), int32(1), object(6)
memory usage: 19.2+ KB

In [165]:
Population_Summary['Migrants']=Population_Summary['Migrants'].str.replace(',','')
Population_Summary['Migrants']=Population_Summary['Migrants'].str.replace('−','-')
Population_Summary['Migrants']=Population_Summary['Migrants'].astype(float)
Population_Summary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233 entries, 0 to 232
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country         233 non-null    object
 1   Population2025  233 non-null    int32
 2   Yearly_change   233 non-null    float64
 3   Net_change      233 non-null    float64
 4   Density         233 non-null    float64
 5   Land_area       233 non-null    float64
 6   Migrants        233 non-null    float64
 7   Fert_rate       233 non-null    object
 8   Median_age      233 non-null    object
 9   Urban_pop       233 non-null    object
 10  World_share     233 non-null    object
dtypes: float64(5), int32(1), object(5)
memory usage: 19.2+ KB

In [166]:
Population_Summary['Fert_rate']=Population_Summary['Fert_rate'].str.replace(',','')
Population_Summary['Fert_rate']=Population_Summary['Fert_rate'].astype(float)
Population_Summary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233 entries, 0 to 232
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country         233 non-null    object
 1   Population2025  233 non-null    int32
 2   Yearly_change   233 non-null    float64
 3   Net_change      233 non-null    float64
 4   Density         233 non-null    float64
 5   Land_area       233 non-null    float64
 6   Migrants        233 non-null    float64
 7   Fert_rate       233 non-null    float64
 8   Median_age      233 non-null    object
 9   Urban_pop       233 non-null    object
 10  World_share     233 non-null    object
dtypes: float64(6), int32(1), object(4)
memory usage: 19.2+ KB

In [167]:
Population_Summary['Median_age']=Population_Summary['Median_age'].str.replace(',','')
Population_Summary['Median_age']=Population_Summary['Median_age'].astype(float)
Population_Summary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233 entries, 0 to 232
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country         233 non-null    object
 1   Population2025  233 non-null    int32
 2   Yearly_change   233 non-null    float64
 3   Net_change      233 non-null    float64
 4   Density         233 non-null    float64
 5   Land_area       233 non-null    float64
 6   Migrants        233 non-null    float64
 7   Fert_rate       233 non-null    float64
 8   Median_age      233 non-null    float64
 9   Urban_pop       233 non-null    object
 10  World_share     233 non-null    object
dtypes: float64(7), int32(1), object(3)
memory usage: 19.2+ KB

In [168]:
Population_Summary['Urban_pop']=Population_Summary['Urban_pop'].str.replace('%','')
Population_Summary['Urban_pop']=Population_Summary['Urban_pop'].str.strip()
Population_Summary['Urban_pop']=pd.to_numeric(Population_Summary['Urban_pop'],errors='coerce')  #astype(float) creashes on '' while to_numerice converts invalid to NaN
Population_Summary['Urban_pop']=Population_Summary['Urban_pop'].astype(float)

Population_Summary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233 entries, 0 to 232
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country         233 non-null    object
 1   Population2025  233 non-null    int32
 2   Yearly_change   233 non-null    float64
 3   Net_change      233 non-null    float64
 4   Density         233 non-null    float64
 5   Land_area       233 non-null    float64
 6   Migrants        233 non-null    float64
 7   Fert_rate       233 non-null    float64
 8   Median_age      233 non-null    float64
 9   Urban_pop       210 non-null    float64
 10  World_share     233 non-null    object
dtypes: float64(8), int32(1), object(2)
memory usage: 19.2+ KB

In [169]:
Population_Summary['World_share']=Population_Summary['World_share'].str.replace('%','')
Population_Summary['World_share']=Population_Summary['World_share'].astype(float)
Population_Summary

,Country,Population2025,Yearly_change,Net_change,Density,Land_area,Migrants,Fert_rate,Median_age,Urban_pop,World_share
0,India,1463865525,0.89,12929734.0,492.0,2973190.0,-495753.0,1.94,28.8,37.1,17.780000
1,China,1416096094,-0.23,-3225184.0,151.0,9388211.0,-268126.0,1.02,40.1,67.5,17.200000
2,United States,347275807,0.54,1849236.0,38.0,9147420.0,1230663.0,1.62,38.5,82.8,4.220000
3,Indonesia,285721236,0.79,2233305.0,158.0,1811570.0,-39509.0,2.10,30.4,59.6,3.470000
4,Pakistan,255219554,1.57,3950390.0,331.0,770880.0,-1235336.0,3.50,20.6,34.4,3.100000
...,...,...,...,...,...,...,...,...,...,...,...
228,Montserrat,4359,-0.68,-30.0,44.0,100.0,-9.0,1.45,41.6,11.5,0.000053
229,Falkland Islands,3469,-0.03,-1.0,0.0,12170.0,-17.0,1.70,42.8,68.0,0.000042
230,Tokelau,2608,4.07,102.0,261.0,10.0,53.0,2.57,27.3,NaN,0.000032
231,Niue,1821,0.11,2.0,7.0,260.0,3.0,2.46,35.7,44.5,0.000022
232,Holy See,501,1.01,5.0,1253.0,0.0,13.0,1.00,57.4,NaN,0.000006

In [170]:
Population_Summary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233 entries, 0 to 232
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country         233 non-null    object
 1   Population2025  233 non-null    int32
 2   Yearly_change   233 non-null    float64
 3   Net_change      233 non-null    float64
 4   Density         233 non-null    float64
 5   Land_area       233 non-null    float64
 6   Migrants        233 non-null    float64
 7   Fert_rate       233 non-null    float64
 8   Median_age      233 non-null    float64
 9   Urban_pop       210 non-null    float64
 10  World_share     233 non-null    float64
dtypes: float64(9), int32(1), object(1)
memory usage: 19.2+ KB

Data Analysis

In [171]:
#Country Which has maximum popualtion
max_population=Population_Summary['Population2025'].max()
Population_Summary.loc[Population_Summary['Population2025']==max_population]

,Country,Population2025,Yearly_change,Net_change,Density,Land_area,Migrants,Fert_rate,Median_age,Urban_pop,World_share
0,India,1463865525,0.89,12929734.0,492.0,2973190.0,-495753.0,1.94,28.8,37.1,17.78

In [172]:
#Country Which has minimum population
min_population=Population_Summary['Population2025'].min()
Population_Summary.loc[Population_Summary['Population2025']==min_population]

,Country,Population2025,Yearly_change,Net_change,Density,Land_area,Migrants,Fert_rate,Median_age,Urban_pop,World_share
232,Holy See,501,1.01,5.0,1253.0,0.0,13.0,1.0,57.4,NaN,0.000006

In [173]:
mean_population=Population_Summary['Population2025'].mean()
Population_Summary.loc[Population_Summary['Population2025']==mean_population]

Empty DataFrame
Columns: [Country, Population2025, Yearly_change, Net_change, Density, Land_area, Migrants, Fert_rate, Median_age, Urban_pop, World_share]
Index: []

In [174]:
max_migrants=Population_Summary['Migrants'].max()
Population_Summary.loc[Population_Summary['Migrants']==max_migrants]

,Country,Population2025,Yearly_change,Net_change,Density,Land_area,Migrants,Fert_rate,Median_age,Urban_pop,World_share
39,Ukraine,38980376,2.96,1120155.0,67.0,579320.0,1702358.0,1.0,41.8,76.8,0.47

In [178]:
Population_Summary.loc[((Population_Summary['Net_change']>40000)&(Population_Summary['Median_age']>40))]

,Country,Population2025,Yearly_change,Net_change,Density,Land_area,Migrants,Fert_rate,Median_age,Urban_pop,World_share
21,United Kingdom,69551332,0.60,413140.0,287.0,241930.0,389911.0,1.54,40.1,84.5,0.84
22,France,66650804,0.15,102274.0,122.0,547557.0,91737.0,1.64,42.3,82.5,0.81
37,Canada,40126723,0.97,384293.0,4.0,9093510.0,326204.0,1.33,40.6,80.2,0.49
39,Ukraine,38980376,2.96,1120155.0,67.0,579320.0,1702358.0,1.00,41.8,76.8,0.47
70,Netherlands,18346819,0.65,118077.0,544.0,33720.0,104681.0,1.44,41.5,88.9,0.22
90,Sweden,10656633,0.47,49634.0,26.0,410340.0,47079.0,1.44,40.3,87.4,0.13
100,Switzerland,8967407,0.51,45426.0,227.0,39516.0,37253.0,1.44,42.9,74.4,0.11

In [179]:
Population_Summary.loc[((Population_Summary['Population2025']>40000)&(Population_Summary['Density']>100))]

,Country,Population2025,Yearly_change,Net_change,Density,Land_area,Migrants,Fert_rate,Median_age,Urban_pop,World_share
0,India,1463865525,0.89,12929734.0,492.0,2973190.0,-495753.0,1.94,28.8,37.1,17.78000
1,China,1416096094,-0.23,-3225184.0,151.0,9388211.0,-268126.0,1.02,40.1,67.5,17.20000
3,Indonesia,285721236,0.79,2233305.0,158.0,1811570.0,-39509.0,2.10,30.4,59.6,3.47000
4,Pakistan,255219554,1.57,3950390.0,331.0,770880.0,-1235336.0,3.50,20.6,34.4,3.10000
5,Nigeria,237527782,2.08,4848304.0,261.0,910770.0,-15258.0,4.30,18.1,54.9,2.89000
...,...,...,...,...,...,...,...,...,...,...,...
207,Saint Kitts & Nevis,46922,0.17,79.0,180.0,260.0,18.0,1.51,36.2,39.4,0.00057
209,American Samoa,46029,-1.57,-736.0,230.0,200.0,-1051.0,2.25,29.0,NaN,0.00056
210,Sint Maarten,43923,1.32,573.0,1292.0,34.0,530.0,1.43,41.8,99.8,0.00053
212,Liechtenstein,40128,0.65,258.0,251.0,160.0,194.0,1.54,44.5,14.7,0.00049
213,Gibraltar,40126,2.03,797.0,4013.0,10.0,549.0,1.88,38.8,88.5,0.00049